package server

import (
	"database/sql"
	"github.com/biruk-ak/clinical-lis/backend/internal/handler"
	"github.com/biruk-ak/clinical-lis/backend/internal/repository"
	"github.com/biruk-ak/clinical-lis/backend/internal/service"
	"github.com/go-chi/chi/v5"
)

// RegisterGenerated mounts all generated module handlers.
func RegisterGenerated(api chi.Router, db *sql.DB) {
	repoSampleRecord01 := repository.NewSampleRecord01Repository(db)
	svcSampleRecord01 := service.NewSampleRecord01Service(repoSampleRecord01)
	handler.NewSampleRecord01Handler(svcSampleRecord01).Routes(api)
	repoSampleRecord02 := repository.NewSampleRecord02Repository(db)
	svcSampleRecord02 := service.NewSampleRecord02Service(repoSampleRecord02)
	handler.NewSampleRecord02Handler(svcSampleRecord02).Routes(api)
	repoSampleRecord03 := repository.NewSampleRecord03Repository(db)
	svcSampleRecord03 := service.NewSampleRecord03Service(repoSampleRecord03)
	handler.NewSampleRecord03Handler(svcSampleRecord03).Routes(api)
	repoSampleRecord04 := repository.NewSampleRecord04Repository(db)
	svcSampleRecord04 := service.NewSampleRecord04Service(repoSampleRecord04)
	handler.NewSampleRecord04Handler(svcSampleRecord04).Routes(api)
	repoSampleRecord05 := repository.NewSampleRecord05Repository(db)
	svcSampleRecord05 := service.NewSampleRecord05Service(repoSampleRecord05)
	handler.NewSampleRecord05Handler(svcSampleRecord05).Routes(api)
	repoSampleRecord06 := repository.NewSampleRecord06Repository(db)
	svcSampleRecord06 := service.NewSampleRecord06Service(repoSampleRecord06)
	handler.NewSampleRecord06Handler(svcSampleRecord06).Routes(api)
	repoSampleRecord07 := repository.NewSampleRecord07Repository(db)
	svcSampleRecord07 := service.NewSampleRecord07Service(repoSampleRecord07)
	handler.NewSampleRecord07Handler(svcSampleRecord07).Routes(api)
	repoSampleRecord08 := repository.NewSampleRecord08Repository(db)
	svcSampleRecord08 := service.NewSampleRecord08Service(repoSampleRecord08)
	handler.NewSampleRecord08Handler(svcSampleRecord08).Routes(api)
	repoSampleRecord09 := repository.NewSampleRecord09Repository(db)
	svcSampleRecord09 := service.NewSampleRecord09Service(repoSampleRecord09)
	handler.NewSampleRecord09Handler(svcSampleRecord09).Routes(api)
	repoSampleRecord10 := repository.NewSampleRecord10Repository(db)
	svcSampleRecord10 := service.NewSampleRecord10Service(repoSampleRecord10)
	handler.NewSampleRecord10Handler(svcSampleRecord10).Routes(api)
	repoSampleRecord11 := repository.NewSampleRecord11Repository(db)
	svcSampleRecord11 := service.NewSampleRecord11Service(repoSampleRecord11)
	handler.NewSampleRecord11Handler(svcSampleRecord11).Routes(api)
	repoSampleRecord12 := repository.NewSampleRecord12Repository(db)
	svcSampleRecord12 := service.NewSampleRecord12Service(repoSampleRecord12)
	handler.NewSampleRecord12Handler(svcSampleRecord12).Routes(api)
	repoSampleRecord13 := repository.NewSampleRecord13Repository(db)
	svcSampleRecord13 := service.NewSampleRecord13Service(repoSampleRecord13)
	handler.NewSampleRecord13Handler(svcSampleRecord13).Routes(api)
	repoSampleRecord14 := repository.NewSampleRecord14Repository(db)
	svcSampleRecord14 := service.NewSampleRecord14Service(repoSampleRecord14)
	handler.NewSampleRecord14Handler(svcSampleRecord14).Routes(api)
	repoSampleRecord15 := repository.NewSampleRecord15Repository(db)
	svcSampleRecord15 := service.NewSampleRecord15Service(repoSampleRecord15)
	handler.NewSampleRecord15Handler(svcSampleRecord15).Routes(api)
	repoSampleRecord16 := repository.NewSampleRecord16Repository(db)
	svcSampleRecord16 := service.NewSampleRecord16Service(repoSampleRecord16)
	handler.NewSampleRecord16Handler(svcSampleRecord16).Routes(api)
	repoSampleRecord17 := repository.NewSampleRecord17Repository(db)
	svcSampleRecord17 := service.NewSampleRecord17Service(repoSampleRecord17)
	handler.NewSampleRecord17Handler(svcSampleRecord17).Routes(api)
	repoSampleRecord18 := repository.NewSampleRecord18Repository(db)
	svcSampleRecord18 := service.NewSampleRecord18Service(repoSampleRecord18)
	handler.NewSampleRecord18Handler(svcSampleRecord18).Routes(api)
	repoSampleRecord19 := repository.NewSampleRecord19Repository(db)
	svcSampleRecord19 := service.NewSampleRecord19Service(repoSampleRecord19)
	handler.NewSampleRecord19Handler(svcSampleRecord19).Routes(api)
	repoSampleRecord20 := repository.NewSampleRecord20Repository(db)
	svcSampleRecord20 := service.NewSampleRecord20Service(repoSampleRecord20)
	handler.NewSampleRecord20Handler(svcSampleRecord20).Routes(api)
	repoSampleRecord21 := repository.NewSampleRecord21Repository(db)
	svcSampleRecord21 := service.NewSampleRecord21Service(repoSampleRecord21)
	handler.NewSampleRecord21Handler(svcSampleRecord21).Routes(api)
	repoSampleRecord22 := repository.NewSampleRecord22Repository(db)
	svcSampleRecord22 := service.NewSampleRecord22Service(repoSampleRecord22)
	handler.NewSampleRecord22Handler(svcSampleRecord22).Routes(api)
	repoSampleRecord23 := repository.NewSampleRecord23Repository(db)
	svcSampleRecord23 := service.NewSampleRecord23Service(repoSampleRecord23)
	handler.NewSampleRecord23Handler(svcSampleRecord23).Routes(api)
	repoSampleRecord24 := repository.NewSampleRecord24Repository(db)
	svcSampleRecord24 := service.NewSampleRecord24Service(repoSampleRecord24)
	handler.NewSampleRecord24Handler(svcSampleRecord24).Routes(api)
	repoSampleRecord25 := repository.NewSampleRecord25Repository(db)
	svcSampleRecord25 := service.NewSampleRecord25Service(repoSampleRecord25)
	handler.NewSampleRecord25Handler(svcSampleRecord25).Routes(api)
	repoSampleRecord26 := repository.NewSampleRecord26Repository(db)
	svcSampleRecord26 := service.NewSampleRecord26Service(repoSampleRecord26)
	handler.NewSampleRecord26Handler(svcSampleRecord26).Routes(api)
	repoSampleRecord27 := repository.NewSampleRecord27Repository(db)
	svcSampleRecord27 := service.NewSampleRecord27Service(repoSampleRecord27)
	handler.NewSampleRecord27Handler(svcSampleRecord27).Routes(api)
	repoSampleRecord28 := repository.NewSampleRecord28Repository(db)
	svcSampleRecord28 := service.NewSampleRecord28Service(repoSampleRecord28)
	handler.NewSampleRecord28Handler(svcSampleRecord28).Routes(api)
	repoLabTestRecord01 := repository.NewLabTestRecord01Repository(db)
	svcLabTestRecord01 := service.NewLabTestRecord01Service(repoLabTestRecord01)
	handler.NewLabTestRecord01Handler(svcLabTestRecord01).Routes(api)
	repoLabTestRecord02 := repository.NewLabTestRecord02Repository(db)
	svcLabTestRecord02 := service.NewLabTestRecord02Service(repoLabTestRecord02)
	handler.NewLabTestRecord02Handler(svcLabTestRecord02).Routes(api)
	repoLabTestRecord03 := repository.NewLabTestRecord03Repository(db)
	svcLabTestRecord03 := service.NewLabTestRecord03Service(repoLabTestRecord03)
	handler.NewLabTestRecord03Handler(svcLabTestRecord03).Routes(api)
	repoLabTestRecord04 := repository.NewLabTestRecord04Repository(db)
	svcLabTestRecord04 := service.NewLabTestRecord04Service(repoLabTestRecord04)
	handler.NewLabTestRecord04Handler(svcLabTestRecord04).Routes(api)
	repoLabTestRecord05 := repository.NewLabTestRecord05Repository(db)
	svcLabTestRecord05 := service.NewLabTestRecord05Service(repoLabTestRecord05)
	handler.NewLabTestRecord05Handler(svcLabTestRecord05).Routes(api)
	repoLabTestRecord06 := repository.NewLabTestRecord06Repository(db)
	svcLabTestRecord06 := service.NewLabTestRecord06Service(repoLabTestRecord06)
	handler.NewLabTestRecord06Handler(svcLabTestRecord06).Routes(api)
	repoLabTestRecord07 := repository.NewLabTestRecord07Repository(db)
	svcLabTestRecord07 := service.NewLabTestRecord07Service(repoLabTestRecord07)
	handler.NewLabTestRecord07Handler(svcLabTestRecord07).Routes(api)
	repoLabTestRecord08 := repository.NewLabTestRecord08Repository(db)
	svcLabTestRecord08 := service.NewLabTestRecord08Service(repoLabTestRecord08)
	handler.NewLabTestRecord08Handler(svcLabTestRecord08).Routes(api)
	repoLabTestRecord09 := repository.NewLabTestRecord09Repository(db)
	svcLabTestRecord09 := service.NewLabTestRecord09Service(repoLabTestRecord09)
	handler.NewLabTestRecord09Handler(svcLabTestRecord09).Routes(api)
	repoLabTestRecord10 := repository.NewLabTestRecord10Repository(db)
	svcLabTestRecord10 := service.NewLabTestRecord10Service(repoLabTestRecord10)
	handler.NewLabTestRecord10Handler(svcLabTestRecord10).Routes(api)
	repoLabTestRecord11 := repository.NewLabTestRecord11Repository(db)
	svcLabTestRecord11 := service.NewLabTestRecord11Service(repoLabTestRecord11)
	handler.NewLabTestRecord11Handler(svcLabTestRecord11).Routes(api)
	repoLabTestRecord12 := repository.NewLabTestRecord12Repository(db)
	svcLabTestRecord12 := service.NewLabTestRecord12Service(repoLabTestRecord12)
	handler.NewLabTestRecord12Handler(svcLabTestRecord12).Routes(api)
	repoLabTestRecord13 := repository.NewLabTestRecord13Repository(db)
	svcLabTestRecord13 := service.NewLabTestRecord13Service(repoLabTestRecord13)
	handler.NewLabTestRecord13Handler(svcLabTestRecord13).Routes(api)
	repoLabTestRecord14 := repository.NewLabTestRecord14Repository(db)
	svcLabTestRecord14 := service.NewLabTestRecord14Service(repoLabTestRecord14)
	handler.NewLabTestRecord14Handler(svcLabTestRecord14).Routes(api)
	repoLabTestRecord15 := repository.NewLabTestRecord15Repository(db)
	svcLabTestRecord15 := service.NewLabTestRecord15Service(repoLabTestRecord15)
	handler.NewLabTestRecord15Handler(svcLabTestRecord15).Routes(api)
	repoLabTestRecord16 := repository.NewLabTestRecord16Repository(db)
	svcLabTestRecord16 := service.NewLabTestRecord16Service(repoLabTestRecord16)
	handler.NewLabTestRecord16Handler(svcLabTestRecord16).Routes(api)
	repoLabTestRecord17 := repository.NewLabTestRecord17Repository(db)
	svcLabTestRecord17 := service.NewLabTestRecord17Service(repoLabTestRecord17)
	handler.NewLabTestRecord17Handler(svcLabTestRecord17).Routes(api)
	repoLabTestRecord18 := repository.NewLabTestRecord18Repository(db)
	svcLabTestRecord18 := service.NewLabTestRecord18Service(repoLabTestRecord18)
	handler.NewLabTestRecord18Handler(svcLabTestRecord18).Routes(api)
	repoLabTestRecord19 := repository.NewLabTestRecord19Repository(db)
	svcLabTestRecord19 := service.NewLabTestRecord19Service(repoLabTestRecord19)
	handler.NewLabTestRecord19Handler(svcLabTestRecord19).Routes(api)
	repoLabTestRecord20 := repository.NewLabTestRecord20Repository(db)
	svcLabTestRecord20 := service.NewLabTestRecord20Service(repoLabTestRecord20)
	handler.NewLabTestRecord20Handler(svcLabTestRecord20).Routes(api)
	repoLabTestRecord21 := repository.NewLabTestRecord21Repository(db)
	svcLabTestRecord21 := service.NewLabTestRecord21Service(repoLabTestRecord21)
	handler.NewLabTestRecord21Handler(svcLabTestRecord21).Routes(api)
	repoLabTestRecord22 := repository.NewLabTestRecord22Repository(db)
	svcLabTestRecord22 := service.NewLabTestRecord22Service(repoLabTestRecord22)
	handler.NewLabTestRecord22Handler(svcLabTestRecord22).Routes(api)
	repoLabTestRecord23 := repository.NewLabTestRecord23Repository(db)
	svcLabTestRecord23 := service.NewLabTestRecord23Service(repoLabTestRecord23)
	handler.NewLabTestRecord23Handler(svcLabTestRecord23).Routes(api)
	repoLabTestRecord24 := repository.NewLabTestRecord24Repository(db)
	svcLabTestRecord24 := service.NewLabTestRecord24Service(repoLabTestRecord24)
	handler.NewLabTestRecord24Handler(svcLabTestRecord24).Routes(api)
	repoLabTestRecord25 := repository.NewLabTestRecord25Repository(db)
	svcLabTestRecord25 := service.NewLabTestRecord25Service(repoLabTestRecord25)
	handler.NewLabTestRecord25Handler(svcLabTestRecord25).Routes(api)
	repoLabTestRecord26 := repository.NewLabTestRecord26Repository(db)
	svcLabTestRecord26 := service.NewLabTestRecord26Service(repoLabTestRecord26)
	handler.NewLabTestRecord26Handler(svcLabTestRecord26).Routes(api)
	repoLabTestRecord27 := repository.NewLabTestRecord27Repository(db)
	svcLabTestRecord27 := service.NewLabTestRecord27Service(repoLabTestRecord27)
	handler.NewLabTestRecord27Handler(svcLabTestRecord27).Routes(api)
	repoLabTestRecord28 := repository.NewLabTestRecord28Repository(db)
	svcLabTestRecord28 := service.NewLabTestRecord28Service(repoLabTestRecord28)
	handler.NewLabTestRecord28Handler(svcLabTestRecord28).Routes(api)
	repoEquipmentRecord01 := repository.NewEquipmentRecord01Repository(db)
	svcEquipmentRecord01 := service.NewEquipmentRecord01Service(repoEquipmentRecord01)
	handler.NewEquipmentRecord01Handler(svcEquipmentRecord01).Routes(api)
	repoEquipmentRecord02 := repository.NewEquipmentRecord02Repository(db)
	svcEquipmentRecord02 := service.NewEquipmentRecord02Service(repoEquipmentRecord02)
	handler.NewEquipmentRecord02Handler(svcEquipmentRecord02).Routes(api)
	repoEquipmentRecord03 := repository.NewEquipmentRecord03Repository(db)
	svcEquipmentRecord03 := service.NewEquipmentRecord03Service(repoEquipmentRecord03)
	handler.NewEquipmentRecord03Handler(svcEquipmentRecord03).Routes(api)
	repoEquipmentRecord04 := repository.NewEquipmentRecord04Repository(db)
	svcEquipmentRecord04 := service.NewEquipmentRecord04Service(repoEquipmentRecord04)
	handler.NewEquipmentRecord04Handler(svcEquipmentRecord04).Routes(api)
	repoEquipmentRecord05 := repository.NewEquipmentRecord05Repository(db)
	svcEquipmentRecord05 := service.NewEquipmentRecord05Service(repoEquipmentRecord05)
	handler.NewEquipmentRecord05Handler(svcEquipmentRecord05).Routes(api)
	repoEquipmentRecord06 := repository.NewEquipmentRecord06Repository(db)
	svcEquipmentRecord06 := service.NewEquipmentRecord06Service(repoEquipmentRecord06)
	handler.NewEquipmentRecord06Handler(svcEquipmentRecord06).Routes(api)
	repoEquipmentRecord07 := repository.NewEquipmentRecord07Repository(db)
	svcEquipmentRecord07 := service.NewEquipmentRecord07Service(repoEquipmentRecord07)
	handler.NewEquipmentRecord07Handler(svcEquipmentRecord07).Routes(api)
	repoEquipmentRecord08 := repository.NewEquipmentRecord08Repository(db)
	svcEquipmentRecord08 := service.NewEquipmentRecord08Service(repoEquipmentRecord08)
	handler.NewEquipmentRecord08Handler(svcEquipmentRecord08).Routes(api)
	repoEquipmentRecord09 := repository.NewEquipmentRecord09Repository(db)
	svcEquipmentRecord09 := service.NewEquipmentRecord09Service(repoEquipmentRecord09)
	handler.NewEquipmentRecord09Handler(svcEquipmentRecord09).Routes(api)
	repoEquipmentRecord10 := repository.NewEquipmentRecord10Repository(db)
	svcEquipmentRecord10 := service.NewEquipmentRecord10Service(repoEquipmentRecord10)
	handler.NewEquipmentRecord10Handler(svcEquipmentRecord10).Routes(api)
	repoEquipmentRecord11 := repository.NewEquipmentRecord11Repository(db)
	svcEquipmentRecord11 := service.NewEquipmentRecord11Service(repoEquipmentRecord11)
	handler.NewEquipmentRecord11Handler(svcEquipmentRecord11).Routes(api)
	repoEquipmentRecord12 := repository.NewEquipmentRecord12Repository(db)
	svcEquipmentRecord12 := service.NewEquipmentRecord12Service(repoEquipmentRecord12)
	handler.NewEquipmentRecord12Handler(svcEquipmentRecord12).Routes(api)
	repoEquipmentRecord13 := repository.NewEquipmentRecord13Repository(db)
	svcEquipmentRecord13 := service.NewEquipmentRecord13Service(repoEquipmentRecord13)
	handler.NewEquipmentRecord13Handler(svcEquipmentRecord13).Routes(api)
	repoEquipmentRecord14 := repository.NewEquipmentRecord14Repository(db)
	svcEquipmentRecord14 := service.NewEquipmentRecord14Service(repoEquipmentRecord14)
	handler.NewEquipmentRecord14Handler(svcEquipmentRecord14).Routes(api)
	repoEquipmentRecord15 := repository.NewEquipmentRecord15Repository(db)
	svcEquipmentRecord15 := service.NewEquipmentRecord15Service(repoEquipmentRecord15)
	handler.NewEquipmentRecord15Handler(svcEquipmentRecord15).Routes(api)
	repoEquipmentRecord16 := repository.NewEquipmentRecord16Repository(db)
	svcEquipmentRecord16 := service.NewEquipmentRecord16Service(repoEquipmentRecord16)
	handler.NewEquipmentRecord16Handler(svcEquipmentRecord16).Routes(api)
	repoEquipmentRecord17 := repository.NewEquipmentRecord17Repository(db)
	svcEquipmentRecord17 := service.NewEquipmentRecord17Service(repoEquipmentRecord17)
	handler.NewEquipmentRecord17Handler(svcEquipmentRecord17).Routes(api)
	repoEquipmentRecord18 := repository.NewEquipmentRecord18Repository(db)
	svcEquipmentRecord18 := service.NewEquipmentRecord18Service(repoEquipmentRecord18)
	handler.NewEquipmentRecord18Handler(svcEquipmentRecord18).Routes(api)
	repoEquipmentRecord19 := repository.NewEquipmentRecord19Repository(db)
	svcEquipmentRecord19 := service.NewEquipmentRecord19Service(repoEquipmentRecord19)
	handler.NewEquipmentRecord19Handler(svcEquipmentRecord19).Routes(api)
	repoEquipmentRecord20 := repository.NewEquipmentRecord20Repository(db)
	svcEquipmentRecord20 := service.NewEquipmentRecord20Service(repoEquipmentRecord20)
	handler.NewEquipmentRecord20Handler(svcEquipmentRecord20).Routes(api)
	repoEquipmentRecord21 := repository.NewEquipmentRecord21Repository(db)
	svcEquipmentRecord21 := service.NewEquipmentRecord21Service(repoEquipmentRecord21)
	handler.NewEquipmentRecord21Handler(svcEquipmentRecord21).Routes(api)
	repoEquipmentRecord22 := repository.NewEquipmentRecord22Repository(db)
	svcEquipmentRecord22 := service.NewEquipmentRecord22Service(repoEquipmentRecord22)
	handler.NewEquipmentRecord22Handler(svcEquipmentRecord22).Routes(api)
	repoEquipmentRecord23 := repository.NewEquipmentRecord23Repository(db)
	svcEquipmentRecord23 := service.NewEquipmentRecord23Service(repoEquipmentRecord23)
	handler.NewEquipmentRecord23Handler(svcEquipmentRecord23).Routes(api)
	repoEquipmentRecord24 := repository.NewEquipmentRecord24Repository(db)
	svcEquipmentRecord24 := service.NewEquipmentRecord24Service(repoEquipmentRecord24)
	handler.NewEquipmentRecord24Handler(svcEquipmentRecord24).Routes(api)
	repoEquipmentRecord25 := repository.NewEquipmentRecord25Repository(db)
	svcEquipmentRecord25 := service.NewEquipmentRecord25Service(repoEquipmentRecord25)
	handler.NewEquipmentRecord25Handler(svcEquipmentRecord25).Routes(api)
	repoEquipmentRecord26 := repository.NewEquipmentRecord26Repository(db)
	svcEquipmentRecord26 := service.NewEquipmentRecord26Service(repoEquipmentRecord26)
	handler.NewEquipmentRecord26Handler(svcEquipmentRecord26).Routes(api)
	repoEquipmentRecord27 := repository.NewEquipmentRecord27Repository(db)
	svcEquipmentRecord27 := service.NewEquipmentRecord27Service(repoEquipmentRecord27)
	handler.NewEquipmentRecord27Handler(svcEquipmentRecord27).Routes(api)
	repoEquipmentRecord28 := repository.NewEquipmentRecord28Repository(db)
	svcEquipmentRecord28 := service.NewEquipmentRecord28Service(repoEquipmentRecord28)
	handler.NewEquipmentRecord28Handler(svcEquipmentRecord28).Routes(api)
	repoResultRecord01 := repository.NewResultRecord01Repository(db)
	svcResultRecord01 := service.NewResultRecord01Service(repoResultRecord01)
	handler.NewResultRecord01Handler(svcResultRecord01).Routes(api)
	repoResultRecord02 := repository.NewResultRecord02Repository(db)
	svcResultRecord02 := service.NewResultRecord02Service(repoResultRecord02)
	handler.NewResultRecord02Handler(svcResultRecord02).Routes(api)
	repoResultRecord03 := repository.NewResultRecord03Repository(db)
	svcResultRecord03 := service.NewResultRecord03Service(repoResultRecord03)
	handler.NewResultRecord03Handler(svcResultRecord03).Routes(api)
	repoResultRecord04 := repository.NewResultRecord04Repository(db)
	svcResultRecord04 := service.NewResultRecord04Service(repoResultRecord04)
	handler.NewResultRecord04Handler(svcResultRecord04).Routes(api)
	repoResultRecord05 := repository.NewResultRecord05Repository(db)
	svcResultRecord05 := service.NewResultRecord05Service(repoResultRecord05)
	handler.NewResultRecord05Handler(svcResultRecord05).Routes(api)
	repoResultRecord06 := repository.NewResultRecord06Repository(db)
	svcResultRecord06 := service.NewResultRecord06Service(repoResultRecord06)
	handler.NewResultRecord06Handler(svcResultRecord06).Routes(api)
	repoResultRecord07 := repository.NewResultRecord07Repository(db)
	svcResultRecord07 := service.NewResultRecord07Service(repoResultRecord07)
	handler.NewResultRecord07Handler(svcResultRecord07).Routes(api)
	repoResultRecord08 := repository.NewResultRecord08Repository(db)
	svcResultRecord08 := service.NewResultRecord08Service(repoResultRecord08)
	handler.NewResultRecord08Handler(svcResultRecord08).Routes(api)
	repoResultRecord09 := repository.NewResultRecord09Repository(db)
	svcResultRecord09 := service.NewResultRecord09Service(repoResultRecord09)
	handler.NewResultRecord09Handler(svcResultRecord09).Routes(api)
	repoResultRecord10 := repository.NewResultRecord10Repository(db)
	svcResultRecord10 := service.NewResultRecord10Service(repoResultRecord10)
	handler.NewResultRecord10Handler(svcResultRecord10).Routes(api)
	repoResultRecord11 := repository.NewResultRecord11Repository(db)
	svcResultRecord11 := service.NewResultRecord11Service(repoResultRecord11)
	handler.NewResultRecord11Handler(svcResultRecord11).Routes(api)
	repoResultRecord12 := repository.NewResultRecord12Repository(db)
	svcResultRecord12 := service.NewResultRecord12Service(repoResultRecord12)
	handler.NewResultRecord12Handler(svcResultRecord12).Routes(api)
	repoResultRecord13 := repository.NewResultRecord13Repository(db)
	svcResultRecord13 := service.NewResultRecord13Service(repoResultRecord13)
	handler.NewResultRecord13Handler(svcResultRecord13).Routes(api)
	repoResultRecord14 := repository.NewResultRecord14Repository(db)
	svcResultRecord14 := service.NewResultRecord14Service(repoResultRecord14)
	handler.NewResultRecord14Handler(svcResultRecord14).Routes(api)
	repoResultRecord15 := repository.NewResultRecord15Repository(db)
	svcResultRecord15 := service.NewResultRecord15Service(repoResultRecord15)
	handler.NewResultRecord15Handler(svcResultRecord15).Routes(api)
	repoResultRecord16 := repository.NewResultRecord16Repository(db)
	svcResultRecord16 := service.NewResultRecord16Service(repoResultRecord16)
	handler.NewResultRecord16Handler(svcResultRecord16).Routes(api)
	repoResultRecord17 := repository.NewResultRecord17Repository(db)
	svcResultRecord17 := service.NewResultRecord17Service(repoResultRecord17)
	handler.NewResultRecord17Handler(svcResultRecord17).Routes(api)
	repoResultRecord18 := repository.NewResultRecord18Repository(db)
	svcResultRecord18 := service.NewResultRecord18Service(repoResultRecord18)
	handler.NewResultRecord18Handler(svcResultRecord18).Routes(api)
	repoResultRecord19 := repository.NewResultRecord19Repository(db)
	svcResultRecord19 := service.NewResultRecord19Service(repoResultRecord19)
	handler.NewResultRecord19Handler(svcResultRecord19).Routes(api)
	repoResultRecord20 := repository.NewResultRecord20Repository(db)
	svcResultRecord20 := service.NewResultRecord20Service(repoResultRecord20)
	handler.NewResultRecord20Handler(svcResultRecord20).Routes(api)
	repoResultRecord21 := repository.NewResultRecord21Repository(db)
	svcResultRecord21 := service.NewResultRecord21Service(repoResultRecord21)
	handler.NewResultRecord21Handler(svcResultRecord21).Routes(api)
	repoResultRecord22 := repository.NewResultRecord22Repository(db)
	svcResultRecord22 := service.NewResultRecord22Service(repoResultRecord22)
	handler.NewResultRecord22Handler(svcResultRecord22).Routes(api)
	repoResultRecord23 := repository.NewResultRecord23Repository(db)
	svcResultRecord23 := service.NewResultRecord23Service(repoResultRecord23)
	handler.NewResultRecord23Handler(svcResultRecord23).Routes(api)
	repoResultRecord24 := repository.NewResultRecord24Repository(db)
	svcResultRecord24 := service.NewResultRecord24Service(repoResultRecord24)
	handler.NewResultRecord24Handler(svcResultRecord24).Routes(api)
	repoResultRecord25 := repository.NewResultRecord25Repository(db)
	svcResultRecord25 := service.NewResultRecord25Service(repoResultRecord25)
	handler.NewResultRecord25Handler(svcResultRecord25).Routes(api)
	repoResultRecord26 := repository.NewResultRecord26Repository(db)
	svcResultRecord26 := service.NewResultRecord26Service(repoResultRecord26)
	handler.NewResultRecord26Handler(svcResultRecord26).Routes(api)
	repoResultRecord27 := repository.NewResultRecord27Repository(db)
	svcResultRecord27 := service.NewResultRecord27Service(repoResultRecord27)
	handler.NewResultRecord27Handler(svcResultRecord27).Routes(api)
	repoResultRecord28 := repository.NewResultRecord28Repository(db)
	svcResultRecord28 := service.NewResultRecord28Service(repoResultRecord28)
	handler.NewResultRecord28Handler(svcResultRecord28).Routes(api)
	repoDoctorRecord01 := repository.NewDoctorRecord01Repository(db)
	svcDoctorRecord01 := service.NewDoctorRecord01Service(repoDoctorRecord01)
	handler.NewDoctorRecord01Handler(svcDoctorRecord01).Routes(api)
	repoDoctorRecord02 := repository.NewDoctorRecord02Repository(db)
	svcDoctorRecord02 := service.NewDoctorRecord02Service(repoDoctorRecord02)
	handler.NewDoctorRecord02Handler(svcDoctorRecord02).Routes(api)
	repoDoctorRecord03 := repository.NewDoctorRecord03Repository(db)
	svcDoctorRecord03 := service.NewDoctorRecord03Service(repoDoctorRecord03)
	handler.NewDoctorRecord03Handler(svcDoctorRecord03).Routes(api)
	repoDoctorRecord04 := repository.NewDoctorRecord04Repository(db)
	svcDoctorRecord04 := service.NewDoctorRecord04Service(repoDoctorRecord04)
	handler.NewDoctorRecord04Handler(svcDoctorRecord04).Routes(api)
	repoDoctorRecord05 := repository.NewDoctorRecord05Repository(db)
	svcDoctorRecord05 := service.NewDoctorRecord05Service(repoDoctorRecord05)
	handler.NewDoctorRecord05Handler(svcDoctorRecord05).Routes(api)
	repoDoctorRecord06 := repository.NewDoctorRecord06Repository(db)
	svcDoctorRecord06 := service.NewDoctorRecord06Service(repoDoctorRecord06)
	handler.NewDoctorRecord06Handler(svcDoctorRecord06).Routes(api)
	repoDoctorRecord07 := repository.NewDoctorRecord07Repository(db)
	svcDoctorRecord07 := service.NewDoctorRecord07Service(repoDoctorRecord07)
	handler.NewDoctorRecord07Handler(svcDoctorRecord07).Routes(api)
	repoDoctorRecord08 := repository.NewDoctorRecord08Repository(db)
	svcDoctorRecord08 := service.NewDoctorRecord08Service(repoDoctorRecord08)
	handler.NewDoctorRecord08Handler(svcDoctorRecord08).Routes(api)
	repoDoctorRecord09 := repository.NewDoctorRecord09Repository(db)
	svcDoctorRecord09 := service.NewDoctorRecord09Service(repoDoctorRecord09)
	handler.NewDoctorRecord09Handler(svcDoctorRecord09).Routes(api)
	repoDoctorRecord10 := repository.NewDoctorRecord10Repository(db)
	svcDoctorRecord10 := service.NewDoctorRecord10Service(repoDoctorRecord10)
	handler.NewDoctorRecord10Handler(svcDoctorRecord10).Routes(api)
	repoDoctorRecord11 := repository.NewDoctorRecord11Repository(db)
	svcDoctorRecord11 := service.NewDoctorRecord11Service(repoDoctorRecord11)
	handler.NewDoctorRecord11Handler(svcDoctorRecord11).Routes(api)
	repoDoctorRecord12 := repository.NewDoctorRecord12Repository(db)
	svcDoctorRecord12 := service.NewDoctorRecord12Service(repoDoctorRecord12)
	handler.NewDoctorRecord12Handler(svcDoctorRecord12).Routes(api)
	repoDoctorRecord13 := repository.NewDoctorRecord13Repository(db)
	svcDoctorRecord13 := service.NewDoctorRecord13Service(repoDoctorRecord13)
	handler.NewDoctorRecord13Handler(svcDoctorRecord13).Routes(api)
	repoDoctorRecord14 := repository.NewDoctorRecord14Repository(db)
	svcDoctorRecord14 := service.NewDoctorRecord14Service(repoDoctorRecord14)
	handler.NewDoctorRecord14Handler(svcDoctorRecord14).Routes(api)
	repoDoctorRecord15 := repository.NewDoctorRecord15Repository(db)
	svcDoctorRecord15 := service.NewDoctorRecord15Service(repoDoctorRecord15)
	handler.NewDoctorRecord15Handler(svcDoctorRecord15).Routes(api)
	repoDoctorRecord16 := repository.NewDoctorRecord16Repository(db)
	svcDoctorRecord16 := service.NewDoctorRecord16Service(repoDoctorRecord16)
	handler.NewDoctorRecord16Handler(svcDoctorRecord16).Routes(api)
	repoDoctorRecord17 := repository.NewDoctorRecord17Repository(db)
	svcDoctorRecord17 := service.NewDoctorRecord17Service(repoDoctorRecord17)
	handler.NewDoctorRecord17Handler(svcDoctorRecord17).Routes(api)
	repoDoctorRecord18 := repository.NewDoctorRecord18Repository(db)
	svcDoctorRecord18 := service.NewDoctorRecord18Service(repoDoctorRecord18)
	handler.NewDoctorRecord18Handler(svcDoctorRecord18).Routes(api)
	repoDoctorRecord19 := repository.NewDoctorRecord19Repository(db)
	svcDoctorRecord19 := service.NewDoctorRecord19Service(repoDoctorRecord19)
	handler.NewDoctorRecord19Handler(svcDoctorRecord19).Routes(api)
	repoDoctorRecord20 := repository.NewDoctorRecord20Repository(db)
	svcDoctorRecord20 := service.NewDoctorRecord20Service(repoDoctorRecord20)
	handler.NewDoctorRecord20Handler(svcDoctorRecord20).Routes(api)
	repoDoctorRecord21 := repository.NewDoctorRecord21Repository(db)
	svcDoctorRecord21 := service.NewDoctorRecord21Service(repoDoctorRecord21)
	handler.NewDoctorRecord21Handler(svcDoctorRecord21).Routes(api)
	repoDoctorRecord22 := repository.NewDoctorRecord22Repository(db)
	svcDoctorRecord22 := service.NewDoctorRecord22Service(repoDoctorRecord22)
	handler.NewDoctorRecord22Handler(svcDoctorRecord22).Routes(api)
	repoDoctorRecord23 := repository.NewDoctorRecord23Repository(db)
	svcDoctorRecord23 := service.NewDoctorRecord23Service(repoDoctorRecord23)
	handler.NewDoctorRecord23Handler(svcDoctorRecord23).Routes(api)
	repoDoctorRecord24 := repository.NewDoctorRecord24Repository(db)
	svcDoctorRecord24 := service.NewDoctorRecord24Service(repoDoctorRecord24)
	handler.NewDoctorRecord24Handler(svcDoctorRecord24).Routes(api)
	repoDoctorRecord25 := repository.NewDoctorRecord25Repository(db)
	svcDoctorRecord25 := service.NewDoctorRecord25Service(repoDoctorRecord25)
	handler.NewDoctorRecord25Handler(svcDoctorRecord25).Routes(api)
	repoDoctorRecord26 := repository.NewDoctorRecord26Repository(db)
	svcDoctorRecord26 := service.NewDoctorRecord26Service(repoDoctorRecord26)
	handler.NewDoctorRecord26Handler(svcDoctorRecord26).Routes(api)
	repoDoctorRecord27 := repository.NewDoctorRecord27Repository(db)
	svcDoctorRecord27 := service.NewDoctorRecord27Service(repoDoctorRecord27)
	handler.NewDoctorRecord27Handler(svcDoctorRecord27).Routes(api)
	repoDoctorRecord28 := repository.NewDoctorRecord28Repository(db)
	svcDoctorRecord28 := service.NewDoctorRecord28Service(repoDoctorRecord28)
	handler.NewDoctorRecord28Handler(svcDoctorRecord28).Routes(api)
	repoHospitalRecord01 := repository.NewHospitalRecord01Repository(db)
	svcHospitalRecord01 := service.NewHospitalRecord01Service(repoHospitalRecord01)
	handler.NewHospitalRecord01Handler(svcHospitalRecord01).Routes(api)
	repoHospitalRecord02 := repository.NewHospitalRecord02Repository(db)
	svcHospitalRecord02 := service.NewHospitalRecord02Service(repoHospitalRecord02)
	handler.NewHospitalRecord02Handler(svcHospitalRecord02).Routes(api)
	repoHospitalRecord03 := repository.NewHospitalRecord03Repository(db)
	svcHospitalRecord03 := service.NewHospitalRecord03Service(repoHospitalRecord03)
	handler.NewHospitalRecord03Handler(svcHospitalRecord03).Routes(api)
	repoHospitalRecord04 := repository.NewHospitalRecord04Repository(db)
	svcHospitalRecord04 := service.NewHospitalRecord04Service(repoHospitalRecord04)
	handler.NewHospitalRecord04Handler(svcHospitalRecord04).Routes(api)
	repoHospitalRecord05 := repository.NewHospitalRecord05Repository(db)
	svcHospitalRecord05 := service.NewHospitalRecord05Service(repoHospitalRecord05)
	handler.NewHospitalRecord05Handler(svcHospitalRecord05).Routes(api)
	repoHospitalRecord06 := repository.NewHospitalRecord06Repository(db)
	svcHospitalRecord06 := service.NewHospitalRecord06Service(repoHospitalRecord06)
	handler.NewHospitalRecord06Handler(svcHospitalRecord06).Routes(api)
	repoHospitalRecord07 := repository.NewHospitalRecord07Repository(db)
	svcHospitalRecord07 := service.NewHospitalRecord07Service(repoHospitalRecord07)
	handler.NewHospitalRecord07Handler(svcHospitalRecord07).Routes(api)
	repoHospitalRecord08 := repository.NewHospitalRecord08Repository(db)
	svcHospitalRecord08 := service.NewHospitalRecord08Service(repoHospitalRecord08)
	handler.NewHospitalRecord08Handler(svcHospitalRecord08).Routes(api)
	repoHospitalRecord09 := repository.NewHospitalRecord09Repository(db)
	svcHospitalRecord09 := service.NewHospitalRecord09Service(repoHospitalRecord09)
	handler.NewHospitalRecord09Handler(svcHospitalRecord09).Routes(api)
	repoHospitalRecord10 := repository.NewHospitalRecord10Repository(db)
	svcHospitalRecord10 := service.NewHospitalRecord10Service(repoHospitalRecord10)
	handler.NewHospitalRecord10Handler(svcHospitalRecord10).Routes(api)
	repoHospitalRecord11 := repository.NewHospitalRecord11Repository(db)
	svcHospitalRecord11 := service.NewHospitalRecord11Service(repoHospitalRecord11)
	handler.NewHospitalRecord11Handler(svcHospitalRecord11).Routes(api)
	repoHospitalRecord12 := repository.NewHospitalRecord12Repository(db)
	svcHospitalRecord12 := service.NewHospitalRecord12Service(repoHospitalRecord12)
	handler.NewHospitalRecord12Handler(svcHospitalRecord12).Routes(api)
	repoHospitalRecord13 := repository.NewHospitalRecord13Repository(db)
	svcHospitalRecord13 := service.NewHospitalRecord13Service(repoHospitalRecord13)
	handler.NewHospitalRecord13Handler(svcHospitalRecord13).Routes(api)
	repoHospitalRecord14 := repository.NewHospitalRecord14Repository(db)
	svcHospitalRecord14 := service.NewHospitalRecord14Service(repoHospitalRecord14)
	handler.NewHospitalRecord14Handler(svcHospitalRecord14).Routes(api)
	repoHospitalRecord15 := repository.NewHospitalRecord15Repository(db)
	svcHospitalRecord15 := service.NewHospitalRecord15Service(repoHospitalRecord15)
	handler.NewHospitalRecord15Handler(svcHospitalRecord15).Routes(api)
	repoHospitalRecord16 := repository.NewHospitalRecord16Repository(db)
	svcHospitalRecord16 := service.NewHospitalRecord16Service(repoHospitalRecord16)
	handler.NewHospitalRecord16Handler(svcHospitalRecord16).Routes(api)
	repoHospitalRecord17 := repository.NewHospitalRecord17Repository(db)
	svcHospitalRecord17 := service.NewHospitalRecord17Service(repoHospitalRecord17)
	handler.NewHospitalRecord17Handler(svcHospitalRecord17).Routes(api)
	repoHospitalRecord18 := repository.NewHospitalRecord18Repository(db)
	svcHospitalRecord18 := service.NewHospitalRecord18Service(repoHospitalRecord18)
	handler.NewHospitalRecord18Handler(svcHospitalRecord18).Routes(api)
	repoHospitalRecord19 := repository.NewHospitalRecord19Repository(db)
	svcHospitalRecord19 := service.NewHospitalRecord19Service(repoHospitalRecord19)
	handler.NewHospitalRecord19Handler(svcHospitalRecord19).Routes(api)
	repoHospitalRecord20 := repository.NewHospitalRecord20Repository(db)
	svcHospitalRecord20 := service.NewHospitalRecord20Service(repoHospitalRecord20)
	handler.NewHospitalRecord20Handler(svcHospitalRecord20).Routes(api)
	repoHospitalRecord21 := repository.NewHospitalRecord21Repository(db)
	svcHospitalRecord21 := service.NewHospitalRecord21Service(repoHospitalRecord21)
	handler.NewHospitalRecord21Handler(svcHospitalRecord21).Routes(api)
	repoHospitalRecord22 := repository.NewHospitalRecord22Repository(db)
	svcHospitalRecord22 := service.NewHospitalRecord22Service(repoHospitalRecord22)
	handler.NewHospitalRecord22Handler(svcHospitalRecord22).Routes(api)
	repoHospitalRecord23 := repository.NewHospitalRecord23Repository(db)
	svcHospitalRecord23 := service.NewHospitalRecord23Service(repoHospitalRecord23)
	handler.NewHospitalRecord23Handler(svcHospitalRecord23).Routes(api)
	repoHospitalRecord24 := repository.NewHospitalRecord24Repository(db)
	svcHospitalRecord24 := service.NewHospitalRecord24Service(repoHospitalRecord24)
	handler.NewHospitalRecord24Handler(svcHospitalRecord24).Routes(api)
	repoHospitalRecord25 := repository.NewHospitalRecord25Repository(db)
	svcHospitalRecord25 := service.NewHospitalRecord25Service(repoHospitalRecord25)
	handler.NewHospitalRecord25Handler(svcHospitalRecord25).Routes(api)
	repoHospitalRecord26 := repository.NewHospitalRecord26Repository(db)
	svcHospitalRecord26 := service.NewHospitalRecord26Service(repoHospitalRecord26)
	handler.NewHospitalRecord26Handler(svcHospitalRecord26).Routes(api)
	repoHospitalRecord27 := repository.NewHospitalRecord27Repository(db)
	svcHospitalRecord27 := service.NewHospitalRecord27Service(repoHospitalRecord27)
	handler.NewHospitalRecord27Handler(svcHospitalRecord27).Routes(api)
	repoHospitalRecord28 := repository.NewHospitalRecord28Repository(db)
	svcHospitalRecord28 := service.NewHospitalRecord28Service(repoHospitalRecord28)
	handler.NewHospitalRecord28Handler(svcHospitalRecord28).Routes(api)
	repoQualityControlRecord01 := repository.NewQualityControlRecord01Repository(db)
	svcQualityControlRecord01 := service.NewQualityControlRecord01Service(repoQualityControlRecord01)
	handler.NewQualityControlRecord01Handler(svcQualityControlRecord01).Routes(api)
	repoQualityControlRecord02 := repository.NewQualityControlRecord02Repository(db)
	svcQualityControlRecord02 := service.NewQualityControlRecord02Service(repoQualityControlRecord02)
	handler.NewQualityControlRecord02Handler(svcQualityControlRecord02).Routes(api)
	repoQualityControlRecord03 := repository.NewQualityControlRecord03Repository(db)
	svcQualityControlRecord03 := service.NewQualityControlRecord03Service(repoQualityControlRecord03)
	handler.NewQualityControlRecord03Handler(svcQualityControlRecord03).Routes(api)
	repoQualityControlRecord04 := repository.NewQualityControlRecord04Repository(db)
	svcQualityControlRecord04 := service.NewQualityControlRecord04Service(repoQualityControlRecord04)
	handler.NewQualityControlRecord04Handler(svcQualityControlRecord04).Routes(api)
	repoQualityControlRecord05 := repository.NewQualityControlRecord05Repository(db)
	svcQualityControlRecord05 := service.NewQualityControlRecord05Service(repoQualityControlRecord05)
	handler.NewQualityControlRecord05Handler(svcQualityControlRecord05).Routes(api)
	repoQualityControlRecord06 := repository.NewQualityControlRecord06Repository(db)
	svcQualityControlRecord06 := service.NewQualityControlRecord06Service(repoQualityControlRecord06)
	handler.NewQualityControlRecord06Handler(svcQualityControlRecord06).Routes(api)
	repoQualityControlRecord07 := repository.NewQualityControlRecord07Repository(db)
	svcQualityControlRecord07 := service.NewQualityControlRecord07Service(repoQualityControlRecord07)
	handler.NewQualityControlRecord07Handler(svcQualityControlRecord07).Routes(api)
	repoQualityControlRecord08 := repository.NewQualityControlRecord08Repository(db)
	svcQualityControlRecord08 := service.NewQualityControlRecord08Service(repoQualityControlRecord08)
	handler.NewQualityControlRecord08Handler(svcQualityControlRecord08).Routes(api)
	repoQualityControlRecord09 := repository.NewQualityControlRecord09Repository(db)
	svcQualityControlRecord09 := service.NewQualityControlRecord09Service(repoQualityControlRecord09)
	handler.NewQualityControlRecord09Handler(svcQualityControlRecord09).Routes(api)
	repoQualityControlRecord10 := repository.NewQualityControlRecord10Repository(db)
	svcQualityControlRecord10 := service.NewQualityControlRecord10Service(repoQualityControlRecord10)
	handler.NewQualityControlRecord10Handler(svcQualityControlRecord10).Routes(api)
	repoQualityControlRecord11 := repository.NewQualityControlRecord11Repository(db)
	svcQualityControlRecord11 := service.NewQualityControlRecord11Service(repoQualityControlRecord11)
	handler.NewQualityControlRecord11Handler(svcQualityControlRecord11).Routes(api)
	repoQualityControlRecord12 := repository.NewQualityControlRecord12Repository(db)
	svcQualityControlRecord12 := service.NewQualityControlRecord12Service(repoQualityControlRecord12)
	handler.NewQualityControlRecord12Handler(svcQualityControlRecord12).Routes(api)
	repoQualityControlRecord13 := repository.NewQualityControlRecord13Repository(db)
	svcQualityControlRecord13 := service.NewQualityControlRecord13Service(repoQualityControlRecord13)
	handler.NewQualityControlRecord13Handler(svcQualityControlRecord13).Routes(api)
	repoQualityControlRecord14 := repository.NewQualityControlRecord14Repository(db)
	svcQualityControlRecord14 := service.NewQualityControlRecord14Service(repoQualityControlRecord14)
	handler.NewQualityControlRecord14Handler(svcQualityControlRecord14).Routes(api)
	repoQualityControlRecord15 := repository.NewQualityControlRecord15Repository(db)
	svcQualityControlRecord15 := service.NewQualityControlRecord15Service(repoQualityControlRecord15)
	handler.NewQualityControlRecord15Handler(svcQualityControlRecord15).Routes(api)
	repoQualityControlRecord16 := repository.NewQualityControlRecord16Repository(db)
	svcQualityControlRecord16 := service.NewQualityControlRecord16Service(repoQualityControlRecord16)
	handler.NewQualityControlRecord16Handler(svcQualityControlRecord16).Routes(api)
	repoQualityControlRecord17 := repository.NewQualityControlRecord17Repository(db)
	svcQualityControlRecord17 := service.NewQualityControlRecord17Service(repoQualityControlRecord17)
	handler.NewQualityControlRecord17Handler(svcQualityControlRecord17).Routes(api)
	repoQualityControlRecord18 := repository.NewQualityControlRecord18Repository(db)
	svcQualityControlRecord18 := service.NewQualityControlRecord18Service(repoQualityControlRecord18)
	handler.NewQualityControlRecord18Handler(svcQualityControlRecord18).Routes(api)
	repoQualityControlRecord19 := repository.NewQualityControlRecord19Repository(db)
	svcQualityControlRecord19 := service.NewQualityControlRecord19Service(repoQualityControlRecord19)
	handler.NewQualityControlRecord19Handler(svcQualityControlRecord19).Routes(api)
	repoQualityControlRecord20 := repository.NewQualityControlRecord20Repository(db)
	svcQualityControlRecord20 := service.NewQualityControlRecord20Service(repoQualityControlRecord20)
	handler.NewQualityControlRecord20Handler(svcQualityControlRecord20).Routes(api)
	repoQualityControlRecord21 := repository.NewQualityControlRecord21Repository(db)
	svcQualityControlRecord21 := service.NewQualityControlRecord21Service(repoQualityControlRecord21)
	handler.NewQualityControlRecord21Handler(svcQualityControlRecord21).Routes(api)
	repoQualityControlRecord22 := repository.NewQualityControlRecord22Repository(db)
	svcQualityControlRecord22 := service.NewQualityControlRecord22Service(repoQualityControlRecord22)
	handler.NewQualityControlRecord22Handler(svcQualityControlRecord22).Routes(api)
	repoQualityControlRecord23 := repository.NewQualityControlRecord23Repository(db)
	svcQualityControlRecord23 := service.NewQualityControlRecord23Service(repoQualityControlRecord23)
	handler.NewQualityControlRecord23Handler(svcQualityControlRecord23).Routes(api)
	repoQualityControlRecord24 := repository.NewQualityControlRecord24Repository(db)
	svcQualityControlRecord24 := service.NewQualityControlRecord24Service(repoQualityControlRecord24)
	handler.NewQualityControlRecord24Handler(svcQualityControlRecord24).Routes(api)
	repoQualityControlRecord25 := repository.NewQualityControlRecord25Repository(db)
	svcQualityControlRecord25 := service.NewQualityControlRecord25Service(repoQualityControlRecord25)
	handler.NewQualityControlRecord25Handler(svcQualityControlRecord25).Routes(api)
	repoQualityControlRecord26 := repository.NewQualityControlRecord26Repository(db)
	svcQualityControlRecord26 := service.NewQualityControlRecord26Service(repoQualityControlRecord26)
	handler.NewQualityControlRecord26Handler(svcQualityControlRecord26).Routes(api)
	repoQualityControlRecord27 := repository.NewQualityControlRecord27Repository(db)
	svcQualityControlRecord27 := service.NewQualityControlRecord27Service(repoQualityControlRecord27)
	handler.NewQualityControlRecord27Handler(svcQualityControlRecord27).Routes(api)
	repoQualityControlRecord28 := repository.NewQualityControlRecord28Repository(db)
	svcQualityControlRecord28 := service.NewQualityControlRecord28Service(repoQualityControlRecord28)
	handler.NewQualityControlRecord28Handler(svcQualityControlRecord28).Routes(api)
	repoReportRecord01 := repository.NewReportRecord01Repository(db)
	svcReportRecord01 := service.NewReportRecord01Service(repoReportRecord01)
	handler.NewReportRecord01Handler(svcReportRecord01).Routes(api)
	repoReportRecord02 := repository.NewReportRecord02Repository(db)
	svcReportRecord02 := service.NewReportRecord02Service(repoReportRecord02)
	handler.NewReportRecord02Handler(svcReportRecord02).Routes(api)
	repoReportRecord03 := repository.NewReportRecord03Repository(db)
	svcReportRecord03 := service.NewReportRecord03Service(repoReportRecord03)
	handler.NewReportRecord03Handler(svcReportRecord03).Routes(api)
	repoReportRecord04 := repository.NewReportRecord04Repository(db)
	svcReportRecord04 := service.NewReportRecord04Service(repoReportRecord04)
	handler.NewReportRecord04Handler(svcReportRecord04).Routes(api)
	repoReportRecord05 := repository.NewReportRecord05Repository(db)
	svcReportRecord05 := service.NewReportRecord05Service(repoReportRecord05)
	handler.NewReportRecord05Handler(svcReportRecord05).Routes(api)
	repoReportRecord06 := repository.NewReportRecord06Repository(db)
	svcReportRecord06 := service.NewReportRecord06Service(repoReportRecord06)
	handler.NewReportRecord06Handler(svcReportRecord06).Routes(api)
	repoReportRecord07 := repository.NewReportRecord07Repository(db)
	svcReportRecord07 := service.NewReportRecord07Service(repoReportRecord07)
	handler.NewReportRecord07Handler(svcReportRecord07).Routes(api)
	repoReportRecord08 := repository.NewReportRecord08Repository(db)
	svcReportRecord08 := service.NewReportRecord08Service(repoReportRecord08)
	handler.NewReportRecord08Handler(svcReportRecord08).Routes(api)
	repoReportRecord09 := repository.NewReportRecord09Repository(db)
	svcReportRecord09 := service.NewReportRecord09Service(repoReportRecord09)
	handler.NewReportRecord09Handler(svcReportRecord09).Routes(api)
	repoReportRecord10 := repository.NewReportRecord10Repository(db)
	svcReportRecord10 := service.NewReportRecord10Service(repoReportRecord10)
	handler.NewReportRecord10Handler(svcReportRecord10).Routes(api)
	repoReportRecord11 := repository.NewReportRecord11Repository(db)
	svcReportRecord11 := service.NewReportRecord11Service(repoReportRecord11)
	handler.NewReportRecord11Handler(svcReportRecord11).Routes(api)
	repoReportRecord12 := repository.NewReportRecord12Repository(db)
	svcReportRecord12 := service.NewReportRecord12Service(repoReportRecord12)
	handler.NewReportRecord12Handler(svcReportRecord12).Routes(api)
	repoReportRecord13 := repository.NewReportRecord13Repository(db)
	svcReportRecord13 := service.NewReportRecord13Service(repoReportRecord13)
	handler.NewReportRecord13Handler(svcReportRecord13).Routes(api)
	repoReportRecord14 := repository.NewReportRecord14Repository(db)
	svcReportRecord14 := service.NewReportRecord14Service(repoReportRecord14)
	handler.NewReportRecord14Handler(svcReportRecord14).Routes(api)
	repoReportRecord15 := repository.NewReportRecord15Repository(db)
	svcReportRecord15 := service.NewReportRecord15Service(repoReportRecord15)
	handler.NewReportRecord15Handler(svcReportRecord15).Routes(api)
	repoReportRecord16 := repository.NewReportRecord16Repository(db)
	svcReportRecord16 := service.NewReportRecord16Service(repoReportRecord16)
	handler.NewReportRecord16Handler(svcReportRecord16).Routes(api)
	repoReportRecord17 := repository.NewReportRecord17Repository(db)
	svcReportRecord17 := service.NewReportRecord17Service(repoReportRecord17)
	handler.NewReportRecord17Handler(svcReportRecord17).Routes(api)
	repoReportRecord18 := repository.NewReportRecord18Repository(db)
	svcReportRecord18 := service.NewReportRecord18Service(repoReportRecord18)
	handler.NewReportRecord18Handler(svcReportRecord18).Routes(api)
	repoReportRecord19 := repository.NewReportRecord19Repository(db)
	svcReportRecord19 := service.NewReportRecord19Service(repoReportRecord19)
	handler.NewReportRecord19Handler(svcReportRecord19).Routes(api)
	repoReportRecord20 := repository.NewReportRecord20Repository(db)
	svcReportRecord20 := service.NewReportRecord20Service(repoReportRecord20)
	handler.NewReportRecord20Handler(svcReportRecord20).Routes(api)
	repoReportRecord21 := repository.NewReportRecord21Repository(db)
	svcReportRecord21 := service.NewReportRecord21Service(repoReportRecord21)
	handler.NewReportRecord21Handler(svcReportRecord21).Routes(api)
	repoReportRecord22 := repository.NewReportRecord22Repository(db)
	svcReportRecord22 := service.NewReportRecord22Service(repoReportRecord22)
	handler.NewReportRecord22Handler(svcReportRecord22).Routes(api)
	repoReportRecord23 := repository.NewReportRecord23Repository(db)
	svcReportRecord23 := service.NewReportRecord23Service(repoReportRecord23)
	handler.NewReportRecord23Handler(svcReportRecord23).Routes(api)
	repoReportRecord24 := repository.NewReportRecord24Repository(db)
	svcReportRecord24 := service.NewReportRecord24Service(repoReportRecord24)
	handler.NewReportRecord24Handler(svcReportRecord24).Routes(api)
	repoReportRecord25 := repository.NewReportRecord25Repository(db)
	svcReportRecord25 := service.NewReportRecord25Service(repoReportRecord25)
	handler.NewReportRecord25Handler(svcReportRecord25).Routes(api)
	repoReportRecord26 := repository.NewReportRecord26Repository(db)
	svcReportRecord26 := service.NewReportRecord26Service(repoReportRecord26)
	handler.NewReportRecord26Handler(svcReportRecord26).Routes(api)
	repoReportRecord27 := repository.NewReportRecord27Repository(db)
	svcReportRecord27 := service.NewReportRecord27Service(repoReportRecord27)
	handler.NewReportRecord27Handler(svcReportRecord27).Routes(api)
	repoReportRecord28 := repository.NewReportRecord28Repository(db)
	svcReportRecord28 := service.NewReportRecord28Service(repoReportRecord28)
	handler.NewReportRecord28Handler(svcReportRecord28).Routes(api)
	repoAnalyticsRecord01 := repository.NewAnalyticsRecord01Repository(db)
	svcAnalyticsRecord01 := service.NewAnalyticsRecord01Service(repoAnalyticsRecord01)
	handler.NewAnalyticsRecord01Handler(svcAnalyticsRecord01).Routes(api)
	repoAnalyticsRecord02 := repository.NewAnalyticsRecord02Repository(db)
	svcAnalyticsRecord02 := service.NewAnalyticsRecord02Service(repoAnalyticsRecord02)
	handler.NewAnalyticsRecord02Handler(svcAnalyticsRecord02).Routes(api)
	repoAnalyticsRecord03 := repository.NewAnalyticsRecord03Repository(db)
	svcAnalyticsRecord03 := service.NewAnalyticsRecord03Service(repoAnalyticsRecord03)
	handler.NewAnalyticsRecord03Handler(svcAnalyticsRecord03).Routes(api)
	repoAnalyticsRecord04 := repository.NewAnalyticsRecord04Repository(db)
	svcAnalyticsRecord04 := service.NewAnalyticsRecord04Service(repoAnalyticsRecord04)
	handler.NewAnalyticsRecord04Handler(svcAnalyticsRecord04).Routes(api)
	repoAnalyticsRecord05 := repository.NewAnalyticsRecord05Repository(db)
	svcAnalyticsRecord05 := service.NewAnalyticsRecord05Service(repoAnalyticsRecord05)
	handler.NewAnalyticsRecord05Handler(svcAnalyticsRecord05).Routes(api)
	repoAnalyticsRecord06 := repository.NewAnalyticsRecord06Repository(db)
	svcAnalyticsRecord06 := service.NewAnalyticsRecord06Service(repoAnalyticsRecord06)
	handler.NewAnalyticsRecord06Handler(svcAnalyticsRecord06).Routes(api)
	repoAnalyticsRecord07 := repository.NewAnalyticsRecord07Repository(db)
	svcAnalyticsRecord07 := service.NewAnalyticsRecord07Service(repoAnalyticsRecord07)
	handler.NewAnalyticsRecord07Handler(svcAnalyticsRecord07).Routes(api)
	repoAnalyticsRecord08 := repository.NewAnalyticsRecord08Repository(db)
	svcAnalyticsRecord08 := service.NewAnalyticsRecord08Service(repoAnalyticsRecord08)
	handler.NewAnalyticsRecord08Handler(svcAnalyticsRecord08).Routes(api)
	repoAnalyticsRecord09 := repository.NewAnalyticsRecord09Repository(db)
	svcAnalyticsRecord09 := service.NewAnalyticsRecord09Service(repoAnalyticsRecord09)
	handler.NewAnalyticsRecord09Handler(svcAnalyticsRecord09).Routes(api)
	repoAnalyticsRecord10 := repository.NewAnalyticsRecord10Repository(db)
	svcAnalyticsRecord10 := service.NewAnalyticsRecord10Service(repoAnalyticsRecord10)
	handler.NewAnalyticsRecord10Handler(svcAnalyticsRecord10).Routes(api)
	repoAnalyticsRecord11 := repository.NewAnalyticsRecord11Repository(db)
	svcAnalyticsRecord11 := service.NewAnalyticsRecord11Service(repoAnalyticsRecord11)
	handler.NewAnalyticsRecord11Handler(svcAnalyticsRecord11).Routes(api)
	repoAnalyticsRecord12 := repository.NewAnalyticsRecord12Repository(db)
	svcAnalyticsRecord12 := service.NewAnalyticsRecord12Service(repoAnalyticsRecord12)
	handler.NewAnalyticsRecord12Handler(svcAnalyticsRecord12).Routes(api)
	repoAnalyticsRecord13 := repository.NewAnalyticsRecord13Repository(db)
	svcAnalyticsRecord13 := service.NewAnalyticsRecord13Service(repoAnalyticsRecord13)
	handler.NewAnalyticsRecord13Handler(svcAnalyticsRecord13).Routes(api)
	repoAnalyticsRecord14 := repository.NewAnalyticsRecord14Repository(db)
	svcAnalyticsRecord14 := service.NewAnalyticsRecord14Service(repoAnalyticsRecord14)
	handler.NewAnalyticsRecord14Handler(svcAnalyticsRecord14).Routes(api)
	repoAnalyticsRecord15 := repository.NewAnalyticsRecord15Repository(db)
	svcAnalyticsRecord15 := service.NewAnalyticsRecord15Service(repoAnalyticsRecord15)
	handler.NewAnalyticsRecord15Handler(svcAnalyticsRecord15).Routes(api)
	repoAnalyticsRecord16 := repository.NewAnalyticsRecord16Repository(db)
	svcAnalyticsRecord16 := service.NewAnalyticsRecord16Service(repoAnalyticsRecord16)
	handler.NewAnalyticsRecord16Handler(svcAnalyticsRecord16).Routes(api)
	repoAnalyticsRecord17 := repository.NewAnalyticsRecord17Repository(db)
	svcAnalyticsRecord17 := service.NewAnalyticsRecord17Service(repoAnalyticsRecord17)
	handler.NewAnalyticsRecord17Handler(svcAnalyticsRecord17).Routes(api)
	repoAnalyticsRecord18 := repository.NewAnalyticsRecord18Repository(db)
	svcAnalyticsRecord18 := service.NewAnalyticsRecord18Service(repoAnalyticsRecord18)
	handler.NewAnalyticsRecord18Handler(svcAnalyticsRecord18).Routes(api)
	repoAnalyticsRecord19 := repository.NewAnalyticsRecord19Repository(db)
	svcAnalyticsRecord19 := service.NewAnalyticsRecord19Service(repoAnalyticsRecord19)
	handler.NewAnalyticsRecord19Handler(svcAnalyticsRecord19).Routes(api)
	repoAnalyticsRecord20 := repository.NewAnalyticsRecord20Repository(db)
	svcAnalyticsRecord20 := service.NewAnalyticsRecord20Service(repoAnalyticsRecord20)
	handler.NewAnalyticsRecord20Handler(svcAnalyticsRecord20).Routes(api)
	repoAnalyticsRecord21 := repository.NewAnalyticsRecord21Repository(db)
	svcAnalyticsRecord21 := service.NewAnalyticsRecord21Service(repoAnalyticsRecord21)
	handler.NewAnalyticsRecord21Handler(svcAnalyticsRecord21).Routes(api)
	repoAnalyticsRecord22 := repository.NewAnalyticsRecord22Repository(db)
	svcAnalyticsRecord22 := service.NewAnalyticsRecord22Service(repoAnalyticsRecord22)
	handler.NewAnalyticsRecord22Handler(svcAnalyticsRecord22).Routes(api)
	repoAnalyticsRecord23 := repository.NewAnalyticsRecord23Repository(db)
	svcAnalyticsRecord23 := service.NewAnalyticsRecord23Service(repoAnalyticsRecord23)
	handler.NewAnalyticsRecord23Handler(svcAnalyticsRecord23).Routes(api)
	repoAnalyticsRecord24 := repository.NewAnalyticsRecord24Repository(db)
	svcAnalyticsRecord24 := service.NewAnalyticsRecord24Service(repoAnalyticsRecord24)
	handler.NewAnalyticsRecord24Handler(svcAnalyticsRecord24).Routes(api)
	repoAnalyticsRecord25 := repository.NewAnalyticsRecord25Repository(db)
	svcAnalyticsRecord25 := service.NewAnalyticsRecord25Service(repoAnalyticsRecord25)
	handler.NewAnalyticsRecord25Handler(svcAnalyticsRecord25).Routes(api)
	repoAnalyticsRecord26 := repository.NewAnalyticsRecord26Repository(db)
	svcAnalyticsRecord26 := service.NewAnalyticsRecord26Service(repoAnalyticsRecord26)
	handler.NewAnalyticsRecord26Handler(svcAnalyticsRecord26).Routes(api)
	repoAnalyticsRecord27 := repository.NewAnalyticsRecord27Repository(db)
	svcAnalyticsRecord27 := service.NewAnalyticsRecord27Service(repoAnalyticsRecord27)
	handler.NewAnalyticsRecord27Handler(svcAnalyticsRecord27).Routes(api)
	repoAnalyticsRecord28 := repository.NewAnalyticsRecord28Repository(db)
	svcAnalyticsRecord28 := service.NewAnalyticsRecord28Service(repoAnalyticsRecord28)
	handler.NewAnalyticsRecord28Handler(svcAnalyticsRecord28).Routes(api)
	repoPatientRecord01 := repository.NewPatientRecord01Repository(db)
	svcPatientRecord01 := service.NewPatientRecord01Service(repoPatientRecord01)
	handler.NewPatientRecord01Handler(svcPatientRecord01).Routes(api)
	repoPatientRecord02 := repository.NewPatientRecord02Repository(db)
	svcPatientRecord02 := service.NewPatientRecord02Service(repoPatientRecord02)
	handler.NewPatientRecord02Handler(svcPatientRecord02).Routes(api)
	repoPatientRecord03 := repository.NewPatientRecord03Repository(db)
	svcPatientRecord03 := service.NewPatientRecord03Service(repoPatientRecord03)
	handler.NewPatientRecord03Handler(svcPatientRecord03).Routes(api)
	repoPatientRecord04 := repository.NewPatientRecord04Repository(db)
	svcPatientRecord04 := service.NewPatientRecord04Service(repoPatientRecord04)
	handler.NewPatientRecord04Handler(svcPatientRecord04).Routes(api)
	repoPatientRecord05 := repository.NewPatientRecord05Repository(db)
	svcPatientRecord05 := service.NewPatientRecord05Service(repoPatientRecord05)
	handler.NewPatientRecord05Handler(svcPatientRecord05).Routes(api)
	repoPatientRecord06 := repository.NewPatientRecord06Repository(db)
	svcPatientRecord06 := service.NewPatientRecord06Service(repoPatientRecord06)
	handler.NewPatientRecord06Handler(svcPatientRecord06).Routes(api)
	repoPatientRecord07 := repository.NewPatientRecord07Repository(db)
	svcPatientRecord07 := service.NewPatientRecord07Service(repoPatientRecord07)
	handler.NewPatientRecord07Handler(svcPatientRecord07).Routes(api)
	repoPatientRecord08 := repository.NewPatientRecord08Repository(db)
	svcPatientRecord08 := service.NewPatientRecord08Service(repoPatientRecord08)
	handler.NewPatientRecord08Handler(svcPatientRecord08).Routes(api)
	repoPatientRecord09 := repository.NewPatientRecord09Repository(db)
	svcPatientRecord09 := service.NewPatientRecord09Service(repoPatientRecord09)
	handler.NewPatientRecord09Handler(svcPatientRecord09).Routes(api)
	repoPatientRecord10 := repository.NewPatientRecord10Repository(db)
	svcPatientRecord10 := service.NewPatientRecord10Service(repoPatientRecord10)
	handler.NewPatientRecord10Handler(svcPatientRecord10).Routes(api)
	repoPatientRecord11 := repository.NewPatientRecord11Repository(db)
	svcPatientRecord11 := service.NewPatientRecord11Service(repoPatientRecord11)
	handler.NewPatientRecord11Handler(svcPatientRecord11).Routes(api)
	repoPatientRecord12 := repository.NewPatientRecord12Repository(db)
	svcPatientRecord12 := service.NewPatientRecord12Service(repoPatientRecord12)
	handler.NewPatientRecord12Handler(svcPatientRecord12).Routes(api)
	repoPatientRecord13 := repository.NewPatientRecord13Repository(db)
	svcPatientRecord13 := service.NewPatientRecord13Service(repoPatientRecord13)
	handler.NewPatientRecord13Handler(svcPatientRecord13).Routes(api)
	repoPatientRecord14 := repository.NewPatientRecord14Repository(db)
	svcPatientRecord14 := service.NewPatientRecord14Service(repoPatientRecord14)
	handler.NewPatientRecord14Handler(svcPatientRecord14).Routes(api)
	repoPatientRecord15 := repository.NewPatientRecord15Repository(db)
	svcPatientRecord15 := service.NewPatientRecord15Service(repoPatientRecord15)
	handler.NewPatientRecord15Handler(svcPatientRecord15).Routes(api)
	repoPatientRecord16 := repository.NewPatientRecord16Repository(db)
	svcPatientRecord16 := service.NewPatientRecord16Service(repoPatientRecord16)
	handler.NewPatientRecord16Handler(svcPatientRecord16).Routes(api)
	repoPatientRecord17 := repository.NewPatientRecord17Repository(db)
	svcPatientRecord17 := service.NewPatientRecord17Service(repoPatientRecord17)
	handler.NewPatientRecord17Handler(svcPatientRecord17).Routes(api)
	repoPatientRecord18 := repository.NewPatientRecord18Repository(db)
	svcPatientRecord18 := service.NewPatientRecord18Service(repoPatientRecord18)
	handler.NewPatientRecord18Handler(svcPatientRecord18).Routes(api)
	repoPatientRecord19 := repository.NewPatientRecord19Repository(db)
	svcPatientRecord19 := service.NewPatientRecord19Service(repoPatientRecord19)
	handler.NewPatientRecord19Handler(svcPatientRecord19).Routes(api)
	repoPatientRecord20 := repository.NewPatientRecord20Repository(db)
	svcPatientRecord20 := service.NewPatientRecord20Service(repoPatientRecord20)
	handler.NewPatientRecord20Handler(svcPatientRecord20).Routes(api)
	repoPatientRecord21 := repository.NewPatientRecord21Repository(db)
	svcPatientRecord21 := service.NewPatientRecord21Service(repoPatientRecord21)
	handler.NewPatientRecord21Handler(svcPatientRecord21).Routes(api)
	repoPatientRecord22 := repository.NewPatientRecord22Repository(db)
	svcPatientRecord22 := service.NewPatientRecord22Service(repoPatientRecord22)
	handler.NewPatientRecord22Handler(svcPatientRecord22).Routes(api)
	repoPatientRecord23 := repository.NewPatientRecord23Repository(db)
	svcPatientRecord23 := service.NewPatientRecord23Service(repoPatientRecord23)
	handler.NewPatientRecord23Handler(svcPatientRecord23).Routes(api)
	repoPatientRecord24 := repository.NewPatientRecord24Repository(db)
	svcPatientRecord24 := service.NewPatientRecord24Service(repoPatientRecord24)
	handler.NewPatientRecord24Handler(svcPatientRecord24).Routes(api)
	repoPatientRecord25 := repository.NewPatientRecord25Repository(db)
	svcPatientRecord25 := service.NewPatientRecord25Service(repoPatientRecord25)
	handler.NewPatientRecord25Handler(svcPatientRecord25).Routes(api)
	repoPatientRecord26 := repository.NewPatientRecord26Repository(db)
	svcPatientRecord26 := service.NewPatientRecord26Service(repoPatientRecord26)
	handler.NewPatientRecord26Handler(svcPatientRecord26).Routes(api)
	repoPatientRecord27 := repository.NewPatientRecord27Repository(db)
	svcPatientRecord27 := service.NewPatientRecord27Service(repoPatientRecord27)
	handler.NewPatientRecord27Handler(svcPatientRecord27).Routes(api)
	repoPatientRecord28 := repository.NewPatientRecord28Repository(db)
	svcPatientRecord28 := service.NewPatientRecord28Service(repoPatientRecord28)
	handler.NewPatientRecord28Handler(svcPatientRecord28).Routes(api)
	repoOrderRecord01 := repository.NewOrderRecord01Repository(db)
	svcOrderRecord01 := service.NewOrderRecord01Service(repoOrderRecord01)
	handler.NewOrderRecord01Handler(svcOrderRecord01).Routes(api)
	repoOrderRecord02 := repository.NewOrderRecord02Repository(db)
	svcOrderRecord02 := service.NewOrderRecord02Service(repoOrderRecord02)
	handler.NewOrderRecord02Handler(svcOrderRecord02).Routes(api)
	repoOrderRecord03 := repository.NewOrderRecord03Repository(db)
	svcOrderRecord03 := service.NewOrderRecord03Service(repoOrderRecord03)
	handler.NewOrderRecord03Handler(svcOrderRecord03).Routes(api)
	repoOrderRecord04 := repository.NewOrderRecord04Repository(db)
	svcOrderRecord04 := service.NewOrderRecord04Service(repoOrderRecord04)
	handler.NewOrderRecord04Handler(svcOrderRecord04).Routes(api)
	repoOrderRecord05 := repository.NewOrderRecord05Repository(db)
	svcOrderRecord05 := service.NewOrderRecord05Service(repoOrderRecord05)
	handler.NewOrderRecord05Handler(svcOrderRecord05).Routes(api)
	repoOrderRecord06 := repository.NewOrderRecord06Repository(db)
	svcOrderRecord06 := service.NewOrderRecord06Service(repoOrderRecord06)
	handler.NewOrderRecord06Handler(svcOrderRecord06).Routes(api)
	repoOrderRecord07 := repository.NewOrderRecord07Repository(db)
	svcOrderRecord07 := service.NewOrderRecord07Service(repoOrderRecord07)
	handler.NewOrderRecord07Handler(svcOrderRecord07).Routes(api)
	repoOrderRecord08 := repository.NewOrderRecord08Repository(db)
	svcOrderRecord08 := service.NewOrderRecord08Service(repoOrderRecord08)
	handler.NewOrderRecord08Handler(svcOrderRecord08).Routes(api)
	repoOrderRecord09 := repository.NewOrderRecord09Repository(db)
	svcOrderRecord09 := service.NewOrderRecord09Service(repoOrderRecord09)
	handler.NewOrderRecord09Handler(svcOrderRecord09).Routes(api)
	repoOrderRecord10 := repository.NewOrderRecord10Repository(db)
	svcOrderRecord10 := service.NewOrderRecord10Service(repoOrderRecord10)
	handler.NewOrderRecord10Handler(svcOrderRecord10).Routes(api)
	repoOrderRecord11 := repository.NewOrderRecord11Repository(db)
	svcOrderRecord11 := service.NewOrderRecord11Service(repoOrderRecord11)
	handler.NewOrderRecord11Handler(svcOrderRecord11).Routes(api)
	repoOrderRecord12 := repository.NewOrderRecord12Repository(db)
	svcOrderRecord12 := service.NewOrderRecord12Service(repoOrderRecord12)
	handler.NewOrderRecord12Handler(svcOrderRecord12).Routes(api)
	repoOrderRecord13 := repository.NewOrderRecord13Repository(db)
	svcOrderRecord13 := service.NewOrderRecord13Service(repoOrderRecord13)
	handler.NewOrderRecord13Handler(svcOrderRecord13).Routes(api)
	repoOrderRecord14 := repository.NewOrderRecord14Repository(db)
	svcOrderRecord14 := service.NewOrderRecord14Service(repoOrderRecord14)
	handler.NewOrderRecord14Handler(svcOrderRecord14).Routes(api)
	repoOrderRecord15 := repository.NewOrderRecord15Repository(db)
	svcOrderRecord15 := service.NewOrderRecord15Service(repoOrderRecord15)
	handler.NewOrderRecord15Handler(svcOrderRecord15).Routes(api)
	repoOrderRecord16 := repository.NewOrderRecord16Repository(db)
	svcOrderRecord16 := service.NewOrderRecord16Service(repoOrderRecord16)
	handler.NewOrderRecord16Handler(svcOrderRecord16).Routes(api)
	repoOrderRecord17 := repository.NewOrderRecord17Repository(db)
	svcOrderRecord17 := service.NewOrderRecord17Service(repoOrderRecord17)
	handler.NewOrderRecord17Handler(svcOrderRecord17).Routes(api)
	repoOrderRecord18 := repository.NewOrderRecord18Repository(db)
	svcOrderRecord18 := service.NewOrderRecord18Service(repoOrderRecord18)
	handler.NewOrderRecord18Handler(svcOrderRecord18).Routes(api)
	repoOrderRecord19 := repository.NewOrderRecord19Repository(db)
	svcOrderRecord19 := service.NewOrderRecord19Service(repoOrderRecord19)
	handler.NewOrderRecord19Handler(svcOrderRecord19).Routes(api)
	repoOrderRecord20 := repository.NewOrderRecord20Repository(db)
	svcOrderRecord20 := service.NewOrderRecord20Service(repoOrderRecord20)
	handler.NewOrderRecord20Handler(svcOrderRecord20).Routes(api)
	repoOrderRecord21 := repository.NewOrderRecord21Repository(db)
	svcOrderRecord21 := service.NewOrderRecord21Service(repoOrderRecord21)
	handler.NewOrderRecord21Handler(svcOrderRecord21).Routes(api)
	repoOrderRecord22 := repository.NewOrderRecord22Repository(db)
	svcOrderRecord22 := service.NewOrderRecord22Service(repoOrderRecord22)
	handler.NewOrderRecord22Handler(svcOrderRecord22).Routes(api)
	repoOrderRecord23 := repository.NewOrderRecord23Repository(db)
	svcOrderRecord23 := service.NewOrderRecord23Service(repoOrderRecord23)
	handler.NewOrderRecord23Handler(svcOrderRecord23).Routes(api)
	repoOrderRecord24 := repository.NewOrderRecord24Repository(db)
	svcOrderRecord24 := service.NewOrderRecord24Service(repoOrderRecord24)
	handler.NewOrderRecord24Handler(svcOrderRecord24).Routes(api)
	repoOrderRecord25 := repository.NewOrderRecord25Repository(db)
	svcOrderRecord25 := service.NewOrderRecord25Service(repoOrderRecord25)
	handler.NewOrderRecord25Handler(svcOrderRecord25).Routes(api)
	repoOrderRecord26 := repository.NewOrderRecord26Repository(db)
	svcOrderRecord26 := service.NewOrderRecord26Service(repoOrderRecord26)
	handler.NewOrderRecord26Handler(svcOrderRecord26).Routes(api)
	repoOrderRecord27 := repository.NewOrderRecord27Repository(db)
	svcOrderRecord27 := service.NewOrderRecord27Service(repoOrderRecord27)
	handler.NewOrderRecord27Handler(svcOrderRecord27).Routes(api)
	repoOrderRecord28 := repository.NewOrderRecord28Repository(db)
	svcOrderRecord28 := service.NewOrderRecord28Service(repoOrderRecord28)
	handler.NewOrderRecord28Handler(svcOrderRecord28).Routes(api)
	repoBillingRecord01 := repository.NewBillingRecord01Repository(db)
	svcBillingRecord01 := service.NewBillingRecord01Service(repoBillingRecord01)
	handler.NewBillingRecord01Handler(svcBillingRecord01).Routes(api)
	repoBillingRecord02 := repository.NewBillingRecord02Repository(db)
	svcBillingRecord02 := service.NewBillingRecord02Service(repoBillingRecord02)
	handler.NewBillingRecord02Handler(svcBillingRecord02).Routes(api)
	repoBillingRecord03 := repository.NewBillingRecord03Repository(db)
	svcBillingRecord03 := service.NewBillingRecord03Service(repoBillingRecord03)
	handler.NewBillingRecord03Handler(svcBillingRecord03).Routes(api)
	repoBillingRecord04 := repository.NewBillingRecord04Repository(db)
	svcBillingRecord04 := service.NewBillingRecord04Service(repoBillingRecord04)
	handler.NewBillingRecord04Handler(svcBillingRecord04).Routes(api)
	repoBillingRecord05 := repository.NewBillingRecord05Repository(db)
	svcBillingRecord05 := service.NewBillingRecord05Service(repoBillingRecord05)
	handler.NewBillingRecord05Handler(svcBillingRecord05).Routes(api)
	repoBillingRecord06 := repository.NewBillingRecord06Repository(db)
	svcBillingRecord06 := service.NewBillingRecord06Service(repoBillingRecord06)
	handler.NewBillingRecord06Handler(svcBillingRecord06).Routes(api)
	repoBillingRecord07 := repository.NewBillingRecord07Repository(db)
	svcBillingRecord07 := service.NewBillingRecord07Service(repoBillingRecord07)
	handler.NewBillingRecord07Handler(svcBillingRecord07).Routes(api)
	repoBillingRecord08 := repository.NewBillingRecord08Repository(db)
	svcBillingRecord08 := service.NewBillingRecord08Service(repoBillingRecord08)
	handler.NewBillingRecord08Handler(svcBillingRecord08).Routes(api)
	repoBillingRecord09 := repository.NewBillingRecord09Repository(db)
	svcBillingRecord09 := service.NewBillingRecord09Service(repoBillingRecord09)
	handler.NewBillingRecord09Handler(svcBillingRecord09).Routes(api)
	repoBillingRecord10 := repository.NewBillingRecord10Repository(db)
	svcBillingRecord10 := service.NewBillingRecord10Service(repoBillingRecord10)
	handler.NewBillingRecord10Handler(svcBillingRecord10).Routes(api)
	repoBillingRecord11 := repository.NewBillingRecord11Repository(db)
	svcBillingRecord11 := service.NewBillingRecord11Service(repoBillingRecord11)
	handler.NewBillingRecord11Handler(svcBillingRecord11).Routes(api)
	repoBillingRecord12 := repository.NewBillingRecord12Repository(db)
	svcBillingRecord12 := service.NewBillingRecord12Service(repoBillingRecord12)
	handler.NewBillingRecord12Handler(svcBillingRecord12).Routes(api)
	repoBillingRecord13 := repository.NewBillingRecord13Repository(db)
	svcBillingRecord13 := service.NewBillingRecord13Service(repoBillingRecord13)
	handler.NewBillingRecord13Handler(svcBillingRecord13).Routes(api)
	repoBillingRecord14 := repository.NewBillingRecord14Repository(db)
	svcBillingRecord14 := service.NewBillingRecord14Service(repoBillingRecord14)
	handler.NewBillingRecord14Handler(svcBillingRecord14).Routes(api)
	repoBillingRecord15 := repository.NewBillingRecord15Repository(db)
	svcBillingRecord15 := service.NewBillingRecord15Service(repoBillingRecord15)
	handler.NewBillingRecord15Handler(svcBillingRecord15).Routes(api)
	repoBillingRecord16 := repository.NewBillingRecord16Repository(db)
	svcBillingRecord16 := service.NewBillingRecord16Service(repoBillingRecord16)
	handler.NewBillingRecord16Handler(svcBillingRecord16).Routes(api)
	repoBillingRecord17 := repository.NewBillingRecord17Repository(db)
	svcBillingRecord17 := service.NewBillingRecord17Service(repoBillingRecord17)
	handler.NewBillingRecord17Handler(svcBillingRecord17).Routes(api)
	repoBillingRecord18 := repository.NewBillingRecord18Repository(db)
	svcBillingRecord18 := service.NewBillingRecord18Service(repoBillingRecord18)
	handler.NewBillingRecord18Handler(svcBillingRecord18).Routes(api)
	repoBillingRecord19 := repository.NewBillingRecord19Repository(db)
	svcBillingRecord19 := service.NewBillingRecord19Service(repoBillingRecord19)
	handler.NewBillingRecord19Handler(svcBillingRecord19).Routes(api)
	repoBillingRecord20 := repository.NewBillingRecord20Repository(db)
	svcBillingRecord20 := service.NewBillingRecord20Service(repoBillingRecord20)
	handler.NewBillingRecord20Handler(svcBillingRecord20).Routes(api)
	repoBillingRecord21 := repository.NewBillingRecord21Repository(db)
	svcBillingRecord21 := service.NewBillingRecord21Service(repoBillingRecord21)
	handler.NewBillingRecord21Handler(svcBillingRecord21).Routes(api)
	repoBillingRecord22 := repository.NewBillingRecord22Repository(db)
	svcBillingRecord22 := service.NewBillingRecord22Service(repoBillingRecord22)
	handler.NewBillingRecord22Handler(svcBillingRecord22).Routes(api)
	repoBillingRecord23 := repository.NewBillingRecord23Repository(db)
	svcBillingRecord23 := service.NewBillingRecord23Service(repoBillingRecord23)
	handler.NewBillingRecord23Handler(svcBillingRecord23).Routes(api)
	repoBillingRecord24 := repository.NewBillingRecord24Repository(db)
	svcBillingRecord24 := service.NewBillingRecord24Service(repoBillingRecord24)
	handler.NewBillingRecord24Handler(svcBillingRecord24).Routes(api)
	repoBillingRecord25 := repository.NewBillingRecord25Repository(db)
	svcBillingRecord25 := service.NewBillingRecord25Service(repoBillingRecord25)
	handler.NewBillingRecord25Handler(svcBillingRecord25).Routes(api)
	repoBillingRecord26 := repository.NewBillingRecord26Repository(db)
	svcBillingRecord26 := service.NewBillingRecord26Service(repoBillingRecord26)
	handler.NewBillingRecord26Handler(svcBillingRecord26).Routes(api)
	repoBillingRecord27 := repository.NewBillingRecord27Repository(db)
	svcBillingRecord27 := service.NewBillingRecord27Service(repoBillingRecord27)
	handler.NewBillingRecord27Handler(svcBillingRecord27).Routes(api)
	repoBillingRecord28 := repository.NewBillingRecord28Repository(db)
	svcBillingRecord28 := service.NewBillingRecord28Service(repoBillingRecord28)
	handler.NewBillingRecord28Handler(svcBillingRecord28).Routes(api)
	repoInventoryRecord01 := repository.NewInventoryRecord01Repository(db)
	svcInventoryRecord01 := service.NewInventoryRecord01Service(repoInventoryRecord01)
	handler.NewInventoryRecord01Handler(svcInventoryRecord01).Routes(api)
	repoInventoryRecord02 := repository.NewInventoryRecord02Repository(db)
	svcInventoryRecord02 := service.NewInventoryRecord02Service(repoInventoryRecord02)
	handler.NewInventoryRecord02Handler(svcInventoryRecord02).Routes(api)
	repoInventoryRecord03 := repository.NewInventoryRecord03Repository(db)
	svcInventoryRecord03 := service.NewInventoryRecord03Service(repoInventoryRecord03)
	handler.NewInventoryRecord03Handler(svcInventoryRecord03).Routes(api)
	repoInventoryRecord04 := repository.NewInventoryRecord04Repository(db)
	svcInventoryRecord04 := service.NewInventoryRecord04Service(repoInventoryRecord04)
	handler.NewInventoryRecord04Handler(svcInventoryRecord04).Routes(api)
	repoInventoryRecord05 := repository.NewInventoryRecord05Repository(db)
	svcInventoryRecord05 := service.NewInventoryRecord05Service(repoInventoryRecord05)
	handler.NewInventoryRecord05Handler(svcInventoryRecord05).Routes(api)
	repoInventoryRecord06 := repository.NewInventoryRecord06Repository(db)
	svcInventoryRecord06 := service.NewInventoryRecord06Service(repoInventoryRecord06)
	handler.NewInventoryRecord06Handler(svcInventoryRecord06).Routes(api)
	repoInventoryRecord07 := repository.NewInventoryRecord07Repository(db)
	svcInventoryRecord07 := service.NewInventoryRecord07Service(repoInventoryRecord07)
	handler.NewInventoryRecord07Handler(svcInventoryRecord07).Routes(api)
	repoInventoryRecord08 := repository.NewInventoryRecord08Repository(db)
	svcInventoryRecord08 := service.NewInventoryRecord08Service(repoInventoryRecord08)
	handler.NewInventoryRecord08Handler(svcInventoryRecord08).Routes(api)
	repoInventoryRecord09 := repository.NewInventoryRecord09Repository(db)
	svcInventoryRecord09 := service.NewInventoryRecord09Service(repoInventoryRecord09)
	handler.NewInventoryRecord09Handler(svcInventoryRecord09).Routes(api)
	repoInventoryRecord10 := repository.NewInventoryRecord10Repository(db)
	svcInventoryRecord10 := service.NewInventoryRecord10Service(repoInventoryRecord10)
	handler.NewInventoryRecord10Handler(svcInventoryRecord10).Routes(api)
	repoInventoryRecord11 := repository.NewInventoryRecord11Repository(db)
	svcInventoryRecord11 := service.NewInventoryRecord11Service(repoInventoryRecord11)
	handler.NewInventoryRecord11Handler(svcInventoryRecord11).Routes(api)
	repoInventoryRecord12 := repository.NewInventoryRecord12Repository(db)
	svcInventoryRecord12 := service.NewInventoryRecord12Service(repoInventoryRecord12)
	handler.NewInventoryRecord12Handler(svcInventoryRecord12).Routes(api)
	repoInventoryRecord13 := repository.NewInventoryRecord13Repository(db)
	svcInventoryRecord13 := service.NewInventoryRecord13Service(repoInventoryRecord13)
	handler.NewInventoryRecord13Handler(svcInventoryRecord13).Routes(api)
	repoInventoryRecord14 := repository.NewInventoryRecord14Repository(db)
	svcInventoryRecord14 := service.NewInventoryRecord14Service(repoInventoryRecord14)
	handler.NewInventoryRecord14Handler(svcInventoryRecord14).Routes(api)
	repoInventoryRecord15 := repository.NewInventoryRecord15Repository(db)
	svcInventoryRecord15 := service.NewInventoryRecord15Service(repoInventoryRecord15)
	handler.NewInventoryRecord15Handler(svcInventoryRecord15).Routes(api)
	repoInventoryRecord16 := repository.NewInventoryRecord16Repository(db)
	svcInventoryRecord16 := service.NewInventoryRecord16Service(repoInventoryRecord16)
	handler.NewInventoryRecord16Handler(svcInventoryRecord16).Routes(api)
	repoInventoryRecord17 := repository.NewInventoryRecord17Repository(db)
	svcInventoryRecord17 := service.NewInventoryRecord17Service(repoInventoryRecord17)
	handler.NewInventoryRecord17Handler(svcInventoryRecord17).Routes(api)
	repoInventoryRecord18 := repository.NewInventoryRecord18Repository(db)
	svcInventoryRecord18 := service.NewInventoryRecord18Service(repoInventoryRecord18)
	handler.NewInventoryRecord18Handler(svcInventoryRecord18).Routes(api)
	repoInventoryRecord19 := repository.NewInventoryRecord19Repository(db)
	svcInventoryRecord19 := service.NewInventoryRecord19Service(repoInventoryRecord19)
	handler.NewInventoryRecord19Handler(svcInventoryRecord19).Routes(api)
	repoInventoryRecord20 := repository.NewInventoryRecord20Repository(db)
	svcInventoryRecord20 := service.NewInventoryRecord20Service(repoInventoryRecord20)
	handler.NewInventoryRecord20Handler(svcInventoryRecord20).Routes(api)
	repoInventoryRecord21 := repository.NewInventoryRecord21Repository(db)
	svcInventoryRecord21 := service.NewInventoryRecord21Service(repoInventoryRecord21)
	handler.NewInventoryRecord21Handler(svcInventoryRecord21).Routes(api)
	repoInventoryRecord22 := repository.NewInventoryRecord22Repository(db)
	svcInventoryRecord22 := service.NewInventoryRecord22Service(repoInventoryRecord22)
	handler.NewInventoryRecord22Handler(svcInventoryRecord22).Routes(api)
	repoInventoryRecord23 := repository.NewInventoryRecord23Repository(db)
	svcInventoryRecord23 := service.NewInventoryRecord23Service(repoInventoryRecord23)
	handler.NewInventoryRecord23Handler(svcInventoryRecord23).Routes(api)
	repoInventoryRecord24 := repository.NewInventoryRecord24Repository(db)
	svcInventoryRecord24 := service.NewInventoryRecord24Service(repoInventoryRecord24)
	handler.NewInventoryRecord24Handler(svcInventoryRecord24).Routes(api)
	repoInventoryRecord25 := repository.NewInventoryRecord25Repository(db)
	svcInventoryRecord25 := service.NewInventoryRecord25Service(repoInventoryRecord25)
	handler.NewInventoryRecord25Handler(svcInventoryRecord25).Routes(api)
	repoInventoryRecord26 := repository.NewInventoryRecord26Repository(db)
	svcInventoryRecord26 := service.NewInventoryRecord26Service(repoInventoryRecord26)
	handler.NewInventoryRecord26Handler(svcInventoryRecord26).Routes(api)
	repoInventoryRecord27 := repository.NewInventoryRecord27Repository(db)
	svcInventoryRecord27 := service.NewInventoryRecord27Service(repoInventoryRecord27)
	handler.NewInventoryRecord27Handler(svcInventoryRecord27).Routes(api)
	repoInventoryRecord28 := repository.NewInventoryRecord28Repository(db)
	svcInventoryRecord28 := service.NewInventoryRecord28Service(repoInventoryRecord28)
	handler.NewInventoryRecord28Handler(svcInventoryRecord28).Routes(api)
	repoAuthRecord01 := repository.NewAuthRecord01Repository(db)
	svcAuthRecord01 := service.NewAuthRecord01Service(repoAuthRecord01)
	handler.NewAuthRecord01Handler(svcAuthRecord01).Routes(api)
	repoAuthRecord02 := repository.NewAuthRecord02Repository(db)
	svcAuthRecord02 := service.NewAuthRecord02Service(repoAuthRecord02)
	handler.NewAuthRecord02Handler(svcAuthRecord02).Routes(api)
	repoAuthRecord03 := repository.NewAuthRecord03Repository(db)
	svcAuthRecord03 := service.NewAuthRecord03Service(repoAuthRecord03)
	handler.NewAuthRecord03Handler(svcAuthRecord03).Routes(api)
	repoAuthRecord04 := repository.NewAuthRecord04Repository(db)
	svcAuthRecord04 := service.NewAuthRecord04Service(repoAuthRecord04)
	handler.NewAuthRecord04Handler(svcAuthRecord04).Routes(api)
	repoAuthRecord05 := repository.NewAuthRecord05Repository(db)
	svcAuthRecord05 := service.NewAuthRecord05Service(repoAuthRecord05)
	handler.NewAuthRecord05Handler(svcAuthRecord05).Routes(api)
	repoAuthRecord06 := repository.NewAuthRecord06Repository(db)
	svcAuthRecord06 := service.NewAuthRecord06Service(repoAuthRecord06)
	handler.NewAuthRecord06Handler(svcAuthRecord06).Routes(api)
	repoAuthRecord07 := repository.NewAuthRecord07Repository(db)
	svcAuthRecord07 := service.NewAuthRecord07Service(repoAuthRecord07)
	handler.NewAuthRecord07Handler(svcAuthRecord07).Routes(api)
	repoAuthRecord08 := repository.NewAuthRecord08Repository(db)
	svcAuthRecord08 := service.NewAuthRecord08Service(repoAuthRecord08)
	handler.NewAuthRecord08Handler(svcAuthRecord08).Routes(api)
	repoAuthRecord09 := repository.NewAuthRecord09Repository(db)
	svcAuthRecord09 := service.NewAuthRecord09Service(repoAuthRecord09)
	handler.NewAuthRecord09Handler(svcAuthRecord09).Routes(api)
	repoAuthRecord10 := repository.NewAuthRecord10Repository(db)
	svcAuthRecord10 := service.NewAuthRecord10Service(repoAuthRecord10)
	handler.NewAuthRecord10Handler(svcAuthRecord10).Routes(api)
	repoAuthRecord11 := repository.NewAuthRecord11Repository(db)
	svcAuthRecord11 := service.NewAuthRecord11Service(repoAuthRecord11)
	handler.NewAuthRecord11Handler(svcAuthRecord11).Routes(api)
	repoAuthRecord12 := repository.NewAuthRecord12Repository(db)
	svcAuthRecord12 := service.NewAuthRecord12Service(repoAuthRecord12)
	handler.NewAuthRecord12Handler(svcAuthRecord12).Routes(api)
	repoAuthRecord13 := repository.NewAuthRecord13Repository(db)
	svcAuthRecord13 := service.NewAuthRecord13Service(repoAuthRecord13)
	handler.NewAuthRecord13Handler(svcAuthRecord13).Routes(api)
	repoAuthRecord14 := repository.NewAuthRecord14Repository(db)
	svcAuthRecord14 := service.NewAuthRecord14Service(repoAuthRecord14)
	handler.NewAuthRecord14Handler(svcAuthRecord14).Routes(api)
	repoAuthRecord15 := repository.NewAuthRecord15Repository(db)
	svcAuthRecord15 := service.NewAuthRecord15Service(repoAuthRecord15)
	handler.NewAuthRecord15Handler(svcAuthRecord15).Routes(api)
	repoAuthRecord16 := repository.NewAuthRecord16Repository(db)
	svcAuthRecord16 := service.NewAuthRecord16Service(repoAuthRecord16)
	handler.NewAuthRecord16Handler(svcAuthRecord16).Routes(api)
	repoAuthRecord17 := repository.NewAuthRecord17Repository(db)
	svcAuthRecord17 := service.NewAuthRecord17Service(repoAuthRecord17)
	handler.NewAuthRecord17Handler(svcAuthRecord17).Routes(api)
	repoAuthRecord18 := repository.NewAuthRecord18Repository(db)
	svcAuthRecord18 := service.NewAuthRecord18Service(repoAuthRecord18)
	handler.NewAuthRecord18Handler(svcAuthRecord18).Routes(api)
	repoAuthRecord19 := repository.NewAuthRecord19Repository(db)
	svcAuthRecord19 := service.NewAuthRecord19Service(repoAuthRecord19)
	handler.NewAuthRecord19Handler(svcAuthRecord19).Routes(api)
	repoAuthRecord20 := repository.NewAuthRecord20Repository(db)
	svcAuthRecord20 := service.NewAuthRecord20Service(repoAuthRecord20)
	handler.NewAuthRecord20Handler(svcAuthRecord20).Routes(api)
	repoAuthRecord21 := repository.NewAuthRecord21Repository(db)
	svcAuthRecord21 := service.NewAuthRecord21Service(repoAuthRecord21)
	handler.NewAuthRecord21Handler(svcAuthRecord21).Routes(api)
	repoAuthRecord22 := repository.NewAuthRecord22Repository(db)
	svcAuthRecord22 := service.NewAuthRecord22Service(repoAuthRecord22)
	handler.NewAuthRecord22Handler(svcAuthRecord22).Routes(api)
	repoAuthRecord23 := repository.NewAuthRecord23Repository(db)
	svcAuthRecord23 := service.NewAuthRecord23Service(repoAuthRecord23)
	handler.NewAuthRecord23Handler(svcAuthRecord23).Routes(api)
	repoAuthRecord24 := repository.NewAuthRecord24Repository(db)
	svcAuthRecord24 := service.NewAuthRecord24Service(repoAuthRecord24)
	handler.NewAuthRecord24Handler(svcAuthRecord24).Routes(api)
	repoAuthRecord25 := repository.NewAuthRecord25Repository(db)
	svcAuthRecord25 := service.NewAuthRecord25Service(repoAuthRecord25)
	handler.NewAuthRecord25Handler(svcAuthRecord25).Routes(api)
	repoAuthRecord26 := repository.NewAuthRecord26Repository(db)
	svcAuthRecord26 := service.NewAuthRecord26Service(repoAuthRecord26)
	handler.NewAuthRecord26Handler(svcAuthRecord26).Routes(api)
	repoAuthRecord27 := repository.NewAuthRecord27Repository(db)
	svcAuthRecord27 := service.NewAuthRecord27Service(repoAuthRecord27)
	handler.NewAuthRecord27Handler(svcAuthRecord27).Routes(api)
	repoAuthRecord28 := repository.NewAuthRecord28Repository(db)
	svcAuthRecord28 := service.NewAuthRecord28Service(repoAuthRecord28)
	handler.NewAuthRecord28Handler(svcAuthRecord28).Routes(api)
	repoNotificationRecord01 := repository.NewNotificationRecord01Repository(db)
	svcNotificationRecord01 := service.NewNotificationRecord01Service(repoNotificationRecord01)
	handler.NewNotificationRecord01Handler(svcNotificationRecord01).Routes(api)
	repoNotificationRecord02 := repository.NewNotificationRecord02Repository(db)
	svcNotificationRecord02 := service.NewNotificationRecord02Service(repoNotificationRecord02)
	handler.NewNotificationRecord02Handler(svcNotificationRecord02).Routes(api)
	repoNotificationRecord03 := repository.NewNotificationRecord03Repository(db)
	svcNotificationRecord03 := service.NewNotificationRecord03Service(repoNotificationRecord03)
	handler.NewNotificationRecord03Handler(svcNotificationRecord03).Routes(api)
	repoNotificationRecord04 := repository.NewNotificationRecord04Repository(db)
	svcNotificationRecord04 := service.NewNotificationRecord04Service(repoNotificationRecord04)
	handler.NewNotificationRecord04Handler(svcNotificationRecord04).Routes(api)
	repoNotificationRecord05 := repository.NewNotificationRecord05Repository(db)
	svcNotificationRecord05 := service.NewNotificationRecord05Service(repoNotificationRecord05)
	handler.NewNotificationRecord05Handler(svcNotificationRecord05).Routes(api)
	repoNotificationRecord06 := repository.NewNotificationRecord06Repository(db)
	svcNotificationRecord06 := service.NewNotificationRecord06Service(repoNotificationRecord06)
	handler.NewNotificationRecord06Handler(svcNotificationRecord06).Routes(api)
	repoNotificationRecord07 := repository.NewNotificationRecord07Repository(db)
	svcNotificationRecord07 := service.NewNotificationRecord07Service(repoNotificationRecord07)
	handler.NewNotificationRecord07Handler(svcNotificationRecord07).Routes(api)
	repoNotificationRecord08 := repository.NewNotificationRecord08Repository(db)
	svcNotificationRecord08 := service.NewNotificationRecord08Service(repoNotificationRecord08)
	handler.NewNotificationRecord08Handler(svcNotificationRecord08).Routes(api)
	repoNotificationRecord09 := repository.NewNotificationRecord09Repository(db)
	svcNotificationRecord09 := service.NewNotificationRecord09Service(repoNotificationRecord09)
	handler.NewNotificationRecord09Handler(svcNotificationRecord09).Routes(api)
	repoNotificationRecord10 := repository.NewNotificationRecord10Repository(db)
	svcNotificationRecord10 := service.NewNotificationRecord10Service(repoNotificationRecord10)
	handler.NewNotificationRecord10Handler(svcNotificationRecord10).Routes(api)
	repoNotificationRecord11 := repository.NewNotificationRecord11Repository(db)
	svcNotificationRecord11 := service.NewNotificationRecord11Service(repoNotificationRecord11)
	handler.NewNotificationRecord11Handler(svcNotificationRecord11).Routes(api)
	repoNotificationRecord12 := repository.NewNotificationRecord12Repository(db)
	svcNotificationRecord12 := service.NewNotificationRecord12Service(repoNotificationRecord12)
	handler.NewNotificationRecord12Handler(svcNotificationRecord12).Routes(api)
	repoNotificationRecord13 := repository.NewNotificationRecord13Repository(db)
	svcNotificationRecord13 := service.NewNotificationRecord13Service(repoNotificationRecord13)
	handler.NewNotificationRecord13Handler(svcNotificationRecord13).Routes(api)
	repoNotificationRecord14 := repository.NewNotificationRecord14Repository(db)
	svcNotificationRecord14 := service.NewNotificationRecord14Service(repoNotificationRecord14)
	handler.NewNotificationRecord14Handler(svcNotificationRecord14).Routes(api)
	repoNotificationRecord15 := repository.NewNotificationRecord15Repository(db)
	svcNotificationRecord15 := service.NewNotificationRecord15Service(repoNotificationRecord15)
	handler.NewNotificationRecord15Handler(svcNotificationRecord15).Routes(api)
	repoNotificationRecord16 := repository.NewNotificationRecord16Repository(db)
	svcNotificationRecord16 := service.NewNotificationRecord16Service(repoNotificationRecord16)
	handler.NewNotificationRecord16Handler(svcNotificationRecord16).Routes(api)
	repoNotificationRecord17 := repository.NewNotificationRecord17Repository(db)
	svcNotificationRecord17 := service.NewNotificationRecord17Service(repoNotificationRecord17)
	handler.NewNotificationRecord17Handler(svcNotificationRecord17).Routes(api)
	repoNotificationRecord18 := repository.NewNotificationRecord18Repository(db)
	svcNotificationRecord18 := service.NewNotificationRecord18Service(repoNotificationRecord18)
	handler.NewNotificationRecord18Handler(svcNotificationRecord18).Routes(api)
	repoNotificationRecord19 := repository.NewNotificationRecord19Repository(db)
	svcNotificationRecord19 := service.NewNotificationRecord19Service(repoNotificationRecord19)
	handler.NewNotificationRecord19Handler(svcNotificationRecord19).Routes(api)
	repoNotificationRecord20 := repository.NewNotificationRecord20Repository(db)
	svcNotificationRecord20 := service.NewNotificationRecord20Service(repoNotificationRecord20)
	handler.NewNotificationRecord20Handler(svcNotificationRecord20).Routes(api)
	repoNotificationRecord21 := repository.NewNotificationRecord21Repository(db)
	svcNotificationRecord21 := service.NewNotificationRecord21Service(repoNotificationRecord21)
	handler.NewNotificationRecord21Handler(svcNotificationRecord21).Routes(api)
	repoNotificationRecord22 := repository.NewNotificationRecord22Repository(db)
	svcNotificationRecord22 := service.NewNotificationRecord22Service(repoNotificationRecord22)
	handler.NewNotificationRecord22Handler(svcNotificationRecord22).Routes(api)
	repoNotificationRecord23 := repository.NewNotificationRecord23Repository(db)
	svcNotificationRecord23 := service.NewNotificationRecord23Service(repoNotificationRecord23)
	handler.NewNotificationRecord23Handler(svcNotificationRecord23).Routes(api)
	repoNotificationRecord24 := repository.NewNotificationRecord24Repository(db)
	svcNotificationRecord24 := service.NewNotificationRecord24Service(repoNotificationRecord24)
	handler.NewNotificationRecord24Handler(svcNotificationRecord24).Routes(api)
	repoNotificationRecord25 := repository.NewNotificationRecord25Repository(db)
	svcNotificationRecord25 := service.NewNotificationRecord25Service(repoNotificationRecord25)
	handler.NewNotificationRecord25Handler(svcNotificationRecord25).Routes(api)
	repoNotificationRecord26 := repository.NewNotificationRecord26Repository(db)
	svcNotificationRecord26 := service.NewNotificationRecord26Service(repoNotificationRecord26)
	handler.NewNotificationRecord26Handler(svcNotificationRecord26).Routes(api)
	repoNotificationRecord27 := repository.NewNotificationRecord27Repository(db)
	svcNotificationRecord27 := service.NewNotificationRecord27Service(repoNotificationRecord27)
	handler.NewNotificationRecord27Handler(svcNotificationRecord27).Routes(api)
	repoNotificationRecord28 := repository.NewNotificationRecord28Repository(db)
	svcNotificationRecord28 := service.NewNotificationRecord28Service(repoNotificationRecord28)
	handler.NewNotificationRecord28Handler(svcNotificationRecord28).Routes(api)
}
